Esri/arcgis-runtime-samples-ios

DownloadTileCacheSample/DownloadTileCacheSample/ViewController.m

The app crashes by just clicking the plus sign on if the initial extent hasn't be changed.
You can reproduce the issue with the following instruction:
1.       Run the application.
2.       Don't change the extent
3.       Click scale “+” to 9, click “+” one more time.

Fixing: The app crashes by just clicking the plus sign on

---

arcgis-ios-sdk-samples/Maps/Display drawing status/MapViewDrawStatusViewController.swift
arcgis-ios-sdk-samples/Maps/Map loaded/MapLoadedViewController.swift

Caused a crash when calling removeObserver on map and opening the Map loaded sample multiple times

changed map variables to optional instead of explicitly unwrapped

---

arcgis-ios-sdk-samples/Scenes/Extrude graphics/ExtrudeGraphicsViewController.swift

- keeping an instance variable for camera starting point to add graphics
- using arc4random_uniform instead of arc4random

Show work in iPads now; even on iPad4

---

arcgis-ios-sdk-samples/Content Display Logic/Controllers/ContentTableViewController.swift

- Observer was not being removed in case of successful resource download

On demand resource KVO crash fix

---

arcgis-ios-sdk-samples/Edit data/Edit feature attachments/AttachmentsListViewController.swift

Instead of retrieving cell on to which image needs to be set, passing it in instead. This is to account for the fact that the fetchData completion handler can get called before the cell is added to the tableview.

Fix for  cocoa-common-sdk/issues/987

---

arcgis-ios-sdk-samples/Analysis/Viewshed (GeoElement)/ViewshedGeoElement.storyboard

Also, the SceneView is anchored so that it doesn't slip behind the navigation bar so that the `Licensed for Developer Use` watermark isn't obscured when it's at the top of the SceneView.

Move the instructions label to an opaque parent view

---

arcgis-ios-sdk-samples/Analysis/Viewshed (GeoElement)/ViewshedGeoElement.storyboard

Really sorry, @mhdostal. I've since learnt a bit more about working with the Safe Area and I think this change is useful.
Now the Instruction View still extends the full width of the main view, but the contained label's leading and trailing edges are now constrained by the safe area. In practice it doesn't affect the label with the default text contents and font sizes, but it's a better practice.
This time I'll re-review immediately, I promise!

Respect safe area for embedded instruction label

---

arcgis-ios-sdk-samples/Analysis/Viewshed (GeoElement)/ViewshedGeoElement.storyboard

Move the instruction label to immediately below the navigation bar, as opposed to leaving a small gap. Required removing the original top constraint (top of label to top of superview top margin) and adding one for the top of label to top of safe area.

Constrain top of label to top of Safe Area, not the superView top margin

---

arcgis-ios-sdk-samples/Content Display Logic/Controllers/SourceCodeViewController.swift

Removes a space that was inserted before the source code, causing the first line to always be offset.
Before: 
After:

Removes an extra space

---

arcgis-ios-sdk-samples/Analysis/Statistical query/StatisticalQueryViewController.swift
arcgis-ios-sdk-samples/Edit data/Delete features (feature service)/DeleteFeaturesViewController.swift
arcgis-ios-sdk-samples/Edit data/Offline edit and sync/OfflineEditingViewController.swift
arcgis-ios-sdk-samples/Maps/Create and save a map/CreateSaveMapViewController.swift
arcgis-ios-sdk-samples/Maps/Generate offline map/GenerateOfflineMapViewController.swift
arcgis-ios-sdk-samples/Maps/Identify layers/IdentifyLayersViewController.swift
arcgis-ios-sdk-samples/Maps/Manage bookmarks/BookmarksViewController.swift

Removes `handler` parameter from UIAlertAction initialization by using either a trailing closure or the default value.
This will make it easier to find usage of other APIs with `handler` in the name.

Removes `handler` parameter from UIAlertAction

---

arcgis-ios-sdk-samples/Shared resources/Libraries/HorizontalPicker/HorizontalPicker.swift

There is no reason for the delegate to be exposed to Objective-C. By removing the `@objc` attribute, there is a small performance and size benefit.

Makes HorizontalPickerDelegate non-objc

---

arcgis-ios-sdk-samples/Shared resources/Libraries/HorizontalPicker/HorizontalColorPicker.swift

There is no reason for the delegate to be exposed to Objective-C. By removing the @objc attribute, there is a small performance and size benefit.

Makes HorizontalColorPickerDelegate non-objc

---

arcgis-ios-sdk-samples/Extensions/Foundation/URL.swift

I missed this during review. Should reference the layer explicitly to match the design.

Update Brest Service URL to reference the layer explicitly

---

arcgis-ios-sdk-samples/Display information/Display grid/DisplayGrid.storyboard
arcgis-ios-sdk-samples/Display information/Display grid/DisplayGridViewController.swift

Previously the settings would be reset everytime the dialogue was opened, not showing accurate values for each setting.

Makes Display Grid settings persist while in the sample.

---

arcgis-ios-sdk-samples.xcodeproj/project.pbxproj

@philium please review
I think it might have gotten dropped at some point (possibly with #416 ?) 
This was causing issues such as magnifier mask , compass location symbol , rotate sketch icon, and other assests the runtime requires not being displayed

added ArcGIS.bundle to the project's target

---

arcgis-ios-sdk-samples.xcodeproj/xcshareddata/xcschemes/arcgis-ios-sdk-samples.xcscheme

This was used to prevent being inundated with log messages, but that issue has been fixed. Removing as it now hides useful log messages.

Removes OS_ACTIVITY_MODE environment variable

---

arcgis-ios-sdk-samples.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings

This allows the project to be built successfully with the Legacy Build System in Xcode 10 beta.

Adds Workspace Settings file

---

arcgis-ios-sdk-samples/Maps/Generate offline map/GenerateOfflineMapViewController.swift

This is a followup to https://github.com/Esri/arcgis-runtime-samples-ios/pull/452 that was suggested by @dg0yal.

Generate Offline Map: Show any table errors as well.

---

arcgis-ios-sdk-samples/Maps/Manage bookmarks/BookmarksViewController.swift

- Removes conformance to `UIAlertViewDelegate`. This was an unnecessary holdover from `UIAlertController`.
- Removes `alertController` property. The alert controller was being stored but not reused. I don't even know if alert controllers can be reused, so I just removed it.
- Dismisses bookmark list before presenting the add bookmark view controller. This fixes a problem where the add button was enabled, but tapping it did nothing.

Manage Bookmarks: Improves add bookmark

---

arcgis-ios-sdk-samples/Extensions/Foundation/URL.swift
arcgis-ios-sdk-samples/Scenes/Feature layer extrusion/FeatureLayerExtrusionViewController.swift

This brings it in line with the macOS [implementation](https://github.com/Esri/arcgis-runtime-samples-macos/tree/v.next/arcgis-runtime-samples-macos/Scenes/Feature%20layer%20extrusion). Includes changes to the extrusion mode and population density expression.

Updates the Feature Layer Extrusion sample

---

arcgis-ios-sdk-samples/Edit data/Edit feature attachments/AttachmentsListViewController.swift
arcgis-ios-sdk-samples/Search/Offline geocode/OfflineGeocodeViewController.swift

These crash in the simulator when running from Xcode. However, the published 100.3.0 app doesn't crash (🤔 any thoughts on that, @philium?).
Either way I think the update is desirable.

Fix references to images retrieved from ArcGIS.bundle.

---

arcgis-ios-sdk-samples/Content Display Logic/Controllers/ContentTableViewController.swift

The problem is that the table view is loaded on demand, so accessing the property causes it to load if it isn't already.

Prevents the table view from being loaded prematurely.

---

arcgis-ios-sdk-samples/Content Display Logic/Model/Sample.swift

The file uses `URL`, but it wasn't being imported.

Adds missing import statement

---

arcgis-ios-sdk-samples/Layers/Identify KML features/README.md

The sample doesn't use a web view anymore.

Identify KML Features: Removes reference to web view in README

---

arcgis-ios-sdk-samples/Content Display Logic/Controllers/SampleInfoViewController.swift

Prior to this change, links would open in the web view itself. But because there were no navigation controls, there was no way to get back to the readme.
Corresponding macOS PR: https://github.com/Esri/arcgis-runtime-samples-macos/pull/217

Opens links in default web browser

---

arcgis-ios-sdk-samples/Maps/Generate offline map/GenerateOfflineMapViewController.swift

Maybe a copy-paste error from GenerateGeodatabaseSample
Not consequential, but it was creating a folder "xxxx.geodatabase" in which the offline map was placed. I thought it was confusing.

fix name of directory for offline map

---

arcgis-ios-sdk-samples/Scenes/Animate 3D graphic/Animate3DGraphicViewController.swift
arcgis-ios-sdk-samples/Scenes/Animate 3D graphic/PlaneStatsViewController.swift

Also uses measurement formatter for display of altitude, heading, pitch, and roll.
I realize you aren't responsible for `PlaneStatsViewController` being so simple, but it is nice to make it pull its own weight. And using measurement formatter for displaying value+symbol is a better pattern to model.

Makes PlaneStatsViewController more useful

---

README.md
arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
arcgis-ios-sdk-samples.xcodeproj/project.xcworkspace/xcshareddata/WorkspaceSettings.xcsettings

Unfortunately it was necessary to revert to using `$HOME` in the framework's path. This means that the framework will once again show as missing (red) in Xcode, even though the project builds successfully.
Note: Once this PR is merged, Xcode 10.1 will be required to build the app.

Use new build system

---

.swiftlint.yml
arcgis-ios-sdk-samples/Analysis/Analyze hotspots/AnalyzeHotspotsViewController.swift
arcgis-ios-sdk-samples/Analysis/Statistical query (group and sort)/StatisticalQueryGroupAndSortViewController.swift
arcgis-ios-sdk-samples/Edit data/Edit feature attachments/EditAttachmentViewController.swift
arcgis-ios-sdk-samples/Edit data/Offline edit and sync/OfflineEditingViewController.swift
arcgis-ios-sdk-samples/Edit data/Update attributes (feature service)/EditAttributesViewController.swift
arcgis-ios-sdk-samples/Edit data/Update geometries (feature service)/EditGeometryViewController.swift
arcgis-ios-sdk-samples/Features/Feature layer rendering mode (map)/FeatureLayerRenderingModeMapViewController.swift
arcgis-ios-sdk-samples/Features/Generate geodatabase/GenerateGeodatabaseViewController.swift
arcgis-ios-sdk-samples/Features/Service feature table (cache)/OnInteractionCacheViewController.swift
arcgis-ios-sdk-samples/Features/Service feature table (no cache)/OnInteractionNoCacheViewController.swift
arcgis-ios-sdk-samples/Layers/WMTS layer/WMTSLayerViewController.swift
arcgis-ios-sdk-samples/Maps/Display device location/CustomContextSheet.swift
arcgis-ios-sdk-samples/Maps/Open map (URL)/OpenMapURLSettingsViewController.swift
arcgis-ios-sdk-samples/Maps/Open map (URL)/OpenMapURLViewController.swift
arcgis-ios-sdk-samples/Route & Directions/Find service area interactive/FindServiceAreaInteractiveVC.swift
arcgis-ios-sdk-samples/Route & Directions/Offline routing/OfflineRoutingViewController.swift
arcgis-ios-sdk-samples/Route & Directions/Route around barriers/RouteAroundBarriersViewController.swift
arcgis-ios-sdk-samples/Scenes/Extrude graphics/ExtrudeGraphicsViewController.swift
arcgis-ios-sdk-samples/Scenes/Scene symbols/SceneSymbolsViewController.swift
arcgis-ios-sdk-samples/Shared resources/Libraries/DemoTouchView/DemoTouchView.swift
arcgis-ios-sdk-samples/Shared resources/Libraries/ExpandableTableViewController/ExpandableTableViewController.swift

@philium I started this before you commented on the macOS version. I think it's a decent rule. Even if you don't want it enabled, I think the app would benefit from the resultant changes.

Enables the identifier_name SwiftLint rule

---

.swiftlint.yml
arcgis-ios-sdk-samples/Edit data/Offline edit and sync/OfflineEditingViewController.swift
arcgis-ios-sdk-samples/Layers/Export tiles/ExportTilesViewController.swift
arcgis-ios-sdk-samples/Maps/Display device location/CustomContextSheet.swift

I enjoy this rule. It's not very becoming to have `TODO` scattered around a sample app.
Two statements I removed outright and the other two I attempted to "do". The issue is that these are in the Export Tiles sample which appears to have a data source error making it unusable.

Enables the todo SwiftLint rule

---

arcgis-ios-sdk-samples/Info.plist

All traffic through these domains is now `https` so we can remove these exceptions. This affects a lot of samples and while there shouldn't be any issues, changing this now lets us have ample time to find bugs before the next release.

Removes ATS exceptions for arcgis.com and arcgisonline.com

---

.swiftlint.yml
arcgis-ios-sdk-samples/Features/Feature layer rendering mode (map)/FeatureLayerRenderingModeMapViewController.swift
arcgis-ios-sdk-samples/Scenes/Extrude graphics/ExtrudeGraphicsViewController.swift
arcgis-ios-sdk-samples/Search/Offline geocode/SanDiegoAddressesViewController.swift

https://github.com/realm/SwiftLint/releases/tag/0.29.1
The warnings didn't appear to come from new default rules, but rather rules we had already implemented that the old version of SwiftLint has missed.
I just went ahead and removed `closure_body_length` since there doesn't seem to be a great way to conform to that rule and it's not critical to enforcing a uniform style, which is our goal with linting.

Fixes warning for SwiftLint v0.29.1

---

arcgis-ios-sdk-samples/Content Display Logic/Controllers/ContentTableViewController.swift
arcgis-ios-sdk-samples/Content Display Logic/Views/DownloadProgressView.swift

It wasn't needed, so it just cause the compiled code to be larger than needed.
Also changed the header to the standard one.

Removes objc attribute from DownloadProgressViewDelegate

---

arcgis-ios-sdk-samples/Content Display Logic/Model/SampleSearchEngine.swift

`SampleSearchEngine` doesn't depend on anything from `UIKit`.

Changes import from UIKit to Foundation

---

arcgis-ios-sdk-samples/Content Display Logic/Controllers/ContentTableViewController.swift

Rather than going through `self` to get it.

Uses progress object provided by the API

---

arcgis-ios-sdk-samples/Search/Offline geocode/OfflineGeocodeViewController.swift

- Renames function to `makeGraphic(point:attributes:)`
- Changes type of `attributes` parameter to match `AGSGraphic.init(geometry:symbol:attributes:)`
- Provides default value of `attributes parameter`
- Uses image literal

Improves GeocodeOfflineViewController.graphicForPoint(_:attributes:)

---

arcgis-ios-sdk-samples/Route & Directions/Route around barriers/RouteAroundBarriersViewController.swift

The Route Around Barriers view controller was animating the layout of its view while the view was appearing on screen. This ensures that the view is fully laid out before appearing.

Route Around Barriers: Prevent animation on appearance

---

arcgis-ios-sdk-samples/Scenes/Animate 3D graphic/Animate3DGraphicViewController.swift

Assigns the measurement value (`Double`) rather than the measurement itself (`NSMeasurement`).

Fix bug in Animate 3D Graphic sample

---

arcgis-ios-sdk-samples/Layers/Identify KML features/IdentifyKMLFeaturesViewController.swift

The fix was necessary due to recent changes to how callouts work.

Identify KML Features: Fix callout by making text view self-sizing

---

arcgis-ios-sdk-samples/Layers/ArcGIS tiled layer (tile cache)/LocalTiledLayerViewController.swift
arcgis-ios-sdk-samples/Layers/ArcGIS tiled layer (tile cache)/TilePackagesListViewController.swift

- Remove implicitly unwrapped arrays.
- Use URLs instead of paths.
- Rename delegate.

Refactor TilePackagesListViewController

---

arcgis-ios-sdk-samples.xcodeproj/project.pbxproj

Prevents a warning when building with Xcode 10.2 since `English` has been deprecated in favor of `en`. This change is backwards compatible with Xcode 10.1.

Change development region from English to en

---

arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
arcgis-ios-sdk-samples.xcodeproj/xcshareddata/xcschemes/arcgis-ios-sdk-samples.xcscheme

This PR updates the project settings to those recommended by Xcode 10.2. This addresses the "Upgrade to Recommended Settings" warning that Xcode 10.2 generates when opening the project. Xcode recommended enabling the `CLANG_ANALYZER_LOCALIZABILITY_NONLOCALIZED` warning, although doing so has no effect since the app is not localized.
These changes are backwards compatible.

Perform Xcode 10.2 upgrade check

---

arcgis-ios-sdk-samples/Display information/Show legend/MILShowLegendViewController.swift

The property was not being used.

Remove MILShowLegendViewController.popover

---

arcgis-ios-sdk-samples/Content Display Logic/Controllers/ContentTableViewController.swift

The documentation for `NSBundleResourceRequestLoadingPriorityUrgent` states the following: "A special value for loading priority informing the system that the user cannot continue until the resources marked with the tags managed by the request are downloaded." Since we don't create the resource request until the user has selected the sample, this seems like an appropriate priority for us to use. Hopefully this will result in users being able to get to the sample faster.

Increase loading priority of bundle resource request

---

arcgis-ios-sdk-samples.xcodeproj/project.pbxproj

Incorrect indentation was introduced as a result of manually resolving a merge conflict. Xcode fixed the indentation, but not right away.

Fix Xcode project indentation

---

arcgis-ios-sdk-samples/Layers/Play a KML Tour/PlayKMLTour.storyboard

I thought for sure bar leading and trailing edges should be constrained to the safe area, but either something has changed or I was mistaken. The leading and trailing edges are now constrained to the superview. This ensures that the toolbar goes from edge to edge horizontally.

Display a KML Tour: Fix toolbar width

---

arcgis-ios-sdk-samples.xcodeproj/project.pbxproj

It was accidentally a member of the app target. I thought I removed it, but obviously not completely. Xcode keeps recommending this change.

Remove PortalItems.plist from Resources

---

arcgis-ios-sdk-samples/Content Display Logic/ContentPList.plist

Fixes a bug where the model could not be found at runtime.

Add Bristol3DModel as dependency of Choose Camera Controller sample

---

Scripts/download-portal-item-data.swift
arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
arcgis-ios-sdk-samples/Content Display Logic/FileTypes.plist

- Adds support for ZIP archived portal items.
- Uses filename suggested by server. The filenames in `PortalItems.plist` are no longer necessary and will be removed at a later date.
- File types are now stored outside of the script.

Update download data script

---

arcgis-ios-sdk-samples/Display information/Unique value renderer/UniqueValueRendererViewController.swift

`self.featureLayer` was being reference before its value had been set.
The first commit fixes the bug. The second commit updates the sample to match the style used in more recent sample implementations.

Fix bug in Unique Value Renderer

---

arcgis-ios-sdk-samples/Content Display Logic/PortalItems.plist

Hosting of the style file has moved to https://www.arcgis.com/home/item.html?id=c78b149a1d52414682c86a5feeb13d30.

Update portal item identifier of mil2525d.stylx

---

arcgis-ios-sdk-samples/Content Display Logic/Controllers/SegmentedViewController.swift
arcgis-ios-sdk-samples/Content Display Logic/Controllers/SourceCodeViewController.swift
arcgis-ios-sdk-samples/Content Display Logic/Custom BarButtonItem/SourceCodeBarButtonItem.swift

Along with a few other properties in the filenames chain.

Make SourceCodeViewController.filenames non-optional

---

arcgis-ios-sdk-samplesTests/Sample Tests/GraphicsOverlayDictionaryRenderer3DViewControllerTests.swift

A failing test was encountered during review of #745. In conversation with @philium, we ascertained that the failure was introduced via #739.
This PR fixes the failing test. 
1. Run existing tests (via Cmd+U) against `v.next`, noting a failure on [this line](https://github.com/Esri/arcgis-runtime-samples-ios/blob/a0efcf50a37c086c543b69ce0ee639783427ecae/arcgis-ios-sdk-samplesTests/Sample%20Tests/GraphicsOverlayDictionaryRenderer3DViewControllerTests.swift#L55).
1. Checkout the PR branch, re-run the test, and confirm that it now passes.
1. Review the code in the revised test, to guard against unintended regressions.

Resolved failing test in MessageParserTests

---

.swiftlint.yml

Removes unrecognized rule (`unused_private_declaration`) and analyzer rule in wrong place (`unused_import`). The analyzer rule may be reintroduced in the right place at a later date.

Improve SwiftLint config

---

.swiftlint.yml
arcgis-ios-sdk-samples/Content Display Logic/Model/SampleSearchEngine.swift
arcgis-ios-sdk-samples/Display information/Read symbols from a mobile style/ReadSymbolsFromMobileStyleSymbolViewController.swift
arcgis-ios-sdk-samples/Display information/Show legend/MILLegendTableViewController.swift
arcgis-ios-sdk-samples/Edit data/Delete features (feature service)/DeleteFeaturesViewController.swift
arcgis-ios-sdk-samples/Edit data/Edit feature attachments/AttachmentsTableViewController.swift
arcgis-ios-sdk-samples/Edit data/Edit features (connected)/EditFeaturesOnlineViewController.swift
arcgis-ios-sdk-samples/Edit data/Offline edit and sync/OfflineEditingViewController.swift
arcgis-ios-sdk-samples/Edit data/Update attributes (feature service)/EditAttributesViewController.swift
arcgis-ios-sdk-samples/Edit data/Update geometries (feature service)/EditGeometryViewController.swift
arcgis-ios-sdk-samples/Features/Add delete related features/RelatedFeaturesViewController.swift
arcgis-ios-sdk-samples/Maps/Generate offline map (overrides)/GenerateOfflineMapOverridesViewController.swift
arcgis-ios-sdk-samples/Maps/Generate offline map/GenerateOfflineMapViewController.swift
arcgis-ios-sdk-samples/Maps/Map loaded/MapLoadedViewController.swift
arcgis-ios-sdk-samples/Maps/Show location history/LocationHistoryViewController.swift
arcgis-ios-sdk-samples/Maps/Take screenshot/MapViewScreenshotViewController.swift
arcgis-ios-sdk-samples/Route & Directions/Route around barriers/RouteAroundBarriersViewController.swift
arcgis-ios-sdk-samples/Search/Find place/FindPlaceViewController.swift

This PR proposes enabling the `unused_closure_parameter` SwiftLint rule, appeases the existing warnings. SwiftLint enables [this rule](https://github.com/realm/SwiftLint/blob/master/Rules.md#unused-closure-parameter) by default, but it is currently explicitly disabled in this project, as observed in this recent [PR review](https://github.com/Esri/arcgis-runtime-samples-ios/pull/758#discussion_r317627980).
- Because this change is being proposed in parallel with another closure-related SwiftLint [change](https://github.com/Esri/arcgis-runtime-samples-ios/pull/765), I have expressed this PR against _that_ base branch (i.e., `sab/lint-trailing_closure`) for review clarity. While this _could_ be merged into that branch prior to merging #765 into `v.next`, we should probably just change the …

Enabled additional SwiftLint rule : unused_closure_parameter

---

arcgis-ios-sdk-samples/Display information/Simple marker symbol/README.metadata.json
arcgis-ios-sdk-samples/Display information/Simple renderer/README.metadata.json
arcgis-ios-sdk-samples/Display information/Sketch on the map/README.metadata.json
arcgis-ios-sdk-samples/Display information/Unique value renderer/README.metadata.json

Make sure the "Display information" category has consistent labels.

Change category labels to lower case

---

README.md

This will allow us to take advantage of iOS 13 and Swift 5.1 features.

Increase Xcode requirement to 11.0

---

arcgis-ios-sdk-samples/Scenes/Open a scene (portal item)/OpenScene.storyboard

Constrains the scene view's leading and trailing edges to the superview rather than the safe area so that the scene extends into the safe area.

Open a Scene (Portal Item): Fix scene view constraints

---

arcgis-ios-sdk-samples/Maps/Mobile map (search and route)/MobileMapViewController.swift

It turns out these three functions are not being used.

Remove unused functions in MobileMapViewController.swift

---

arcgis-ios-sdk-samples/Scenes/Extrude graphics/ExtrudeGraphicsViewController.swift
arcgis-ios-sdk-samples/Scenes/Surface placements/SurfacePlacementsViewController.swift

The case `draped` has been deprecated.

Replace usage of AGSSurfacePlacement.draped with drapedBillboarded

---

arcgis-ios-sdk-samples/Geometry/Cut geometry/CutGeometryViewController.swift

This addresses a linter issue generated by newer versions of SwiftLint.

Remove extra forward slashes

---

arcgis-ios-sdk-samples/Cloud & Portal/Search for webmap by keyword/SearchForWebmapByKeywordViewController.swift

This PR solves a previous issue that causes search bar background color blend with the navigation bar, which also happens in `SearchForWebmapByKeywordViewController`

Search bar text field background color changed for SearchForWebmapByKeywordViewController

---

arcgis-ios-sdk-samples/Geometry/Convex hull/README.md

Remove redundant number in the list.
I just found the typo when I was reviewing the README, and removed it immediately. 
Sorry for the trouble.

Convex hull README fix

---

arcgis-ios-sdk-samples/Content Display Logic/ContentPList.plist

In #830 at [this commit](https://github.com/Esri/arcgis-runtime-samples-ios/pull/830/commits/f02101ca34441b2c6d10e69e74b4fbc7158c82ee), I removed the entry by accident. 
Add it back now, and would need to require @saratchandrakarumuri to do another check for the example in #826 , to make sure it is working correctly right now.

Add back the accidentally removed plist entry in the app

---

arcgis-ios-sdk-samples/Analysis/Analyze hotspots/AnalyzeHotspotsViewController.swift
arcgis-ios-sdk-samples/Layers/Dictionary renderer with feature layer/FeatureLayerDictionaryRendererViewController.swift

Refactor previous code that does not add a `weak` keyword to the capture list, which could hold a strong reference to the ViewController itself.

Fix strong reference with weak capture in closures

---

arcgis-ios-sdk-samples/Shared resources/Libraries/DemoTouchManager/DemoTouchManager.swift

This PR addresses the following warning that is generated when building with Xcode 11.4:

Address Xcode 11.4 warnings

---

arcgis-ios-sdk-samples/Augmented reality/Collect data in AR/CollectDataAR.storyboard
arcgis-ios-sdk-samples/Augmented reality/Collect data in AR/CollectDataAR.swift
arcgis-ios-sdk-samples/Augmented reality/Display scenes in tabletop AR/DisplayScenesInTabletopAR.storyboard
arcgis-ios-sdk-samples/Augmented reality/Explore scenes in flyover AR/ExploreScenesInFlyoverAR.storyboard

In the 3 AR examples, the info `UILabel`s' background does not extend into the safe area correctly. Also, the `ArcGISARView` the `Collect data AR` example overlap with the toolbar and labels incorrectly. This PR address those issues.
Below attached the screenshot comparisons between original and fixed versions.
|Original|After fix|
|------ | ------|
|<img width=375 src="https://user-images.githubusercontent.com/9660181/78412237-7def5500-75c7-11ea-8ca8-a93a481b1bf8.png">|<img width=375 src="https://user-images.githubusercontent.com/9660181/78412235-7c259180-75c7-11ea-9254-b5029ed61dcf.png">|
|Original|After fix|
|------ | ------|
|<img width=375 src="https://user-images.githubusercontent.com/9660181/78412301-af682080-75c7-11ea-9c37-aed0b15579a6.png">|<img width=375 …

UILabel safe area fix

---

arcgis-ios-sdk-samples/Maps/Download preplanned map/MapSelectionTableViewController.swift

This PR fixes the issue that in `Download preplanned map area` sample, no feature layer is displayed for offline preplanned maps. This is due to the `AGSDownloadPreplannedOfflineMapParameters.updateMode` need to be set explicitly.

Fix: missing feature layer in Download preplanned map area sample

---

arcgis-ios-sdk-samples.xcodeproj/project.pbxproj

In the sample `Display device location`, one of the source file is not added to the copy file build phase, and was not displayed in the code pane.
Added the file back to project file.
Found this issue when dealing with the project file. Check the screen recording below.

Fix: Display device location

---

arcgis-ios-sdk-samples/Scenes/Change atmosphere effect/ChangeAtmosphereEffectViewController.swift

Problem: Cannot dismiss the `OptionsTableViewController` by tapping on the scene.
Cause: This issue was caused by not setting the `passthroughViews` property of the popover VC properly. See the screenshots below.
Fix: Setting the `passthroughViews` properly.
Also went through the app and checked all other samples that used `OptionsTableViewController` and didn't find another problem like this.
|`Bug`|`Fixed`|
|:------:|:------:|
|<img src="https://user-images.githubusercontent.com/9660181/81754914-27015900-946c-11ea-943d-5dc7b140ff11.gif">|<img src="https://user-images.githubusercontent.com/9660181/81754909-236dd200-946c-11ea-8214-7a5feed1121c.gif">|

Fix: OptionsTableViewController cannot dismiss properly

---

README.md

A few updates to the top level README to reflect changes in 100.8 release: #871.
Also,  the URL atop the repo should be updated to https://developers.arcgis.com/ios/latest/. See below

Update top level README for 100.8 release

---

arcgis-ios-sdk-samples/Geometry/Convex hull/ConvexHullViewController.swift

**Bug**: Creating a convex hull after wrapping around the meridian has incorrect behavior with points in web mercator. 
**Fix**: Fixed by normalizing the multipoint geometry before computing the convex hull.
**Ref**: /common-samples/issues/1922
|`Before fix`|`After fix`|
|:------:|:------:|
|<img src="https://user-images.githubusercontent.com/9660181/82248304-bf7c5b00-98fc-11ea-89a8-39286815e5c2.gif">|<img src="https://user-images.githubusercontent.com/9660181/82248300-be4b2e00-98fc-11ea-9f77-dfcf37431437.gif">|

Fix: Convex hull wraparound across meridian

---

Scripts/download-portal-item-data.swift

This PR updates the `download-portal-item-data.swift` script which currently handles the offline data on-demand download for the app. It
- Improves support for ZIP archived portal items.
- Added logics to detect if a file already exists.
A few concerns below.
---
**Edit**: With "-j" argument, no enclosing folder will be created.
`enclosing`
```
.
|---enclosing_folder
|---1.png
|---2.png
| ...
```
`flat`
```
.
|---1.png
|---2.png
| ...
```
One downside is that if the files in archive are already wrapped by an enclosing folder, this method will create an effect such as below.
```
.
|---created_enclosing_folder
|---original_enclosing_folder
|---1.png
|---2.png
| ...
```
Unless the script can handle the case that subfolder is only created for a "flat" archive.
**Edit**: Removed unused …

Update download script for archive with multiple files

---

arcgis-ios-sdk-samples/Geometry/Nearest vertex/NearestVertexViewController.swift

**Description**: Similar to the `Convex hull` sample, this sample also has trouble providing correct coordinates after wrapping around meridian. This bugfix normalizes the point before calling `GeometryEngine`. Also clean up formatting a bit. Refer to #882 .
**Bug**: Calculating a nearest vertex after wrapping around the meridian has incorrect behavior with points in web mercator.
**Fix**: Fixed by normalizing the map point before computing.
**Ref**: /common-samples/issues/2003
|`Before fix`|`After fix`|
|:------:|:------:|
|<img src="https://user-images.githubusercontent.com/9660181/83791298-6af01400-a64e-11ea-86fa-c165f71980f0.gif">|<img src="https://user-images.githubusercontent.com/9660181/83791252-5744ad80-a64e-11ea-9e95-bb47243daaed.gif">|

Fix: Nearest vertex wraparound

---

arcgis-ios-sdk-samples/Info.plist
arcgis-ios-sdk-samples/Shared resources/Libraries/DemoTouchManager/DemoTouchManager.swift

Show Touches is broken in Samples app with magic mouse or trackpad. Tapping/Clicking on multiple points doesn't remove the previous touches. The pointer is already visible, so we don't need to show touches in that scenario.

do not show touches for indirect pointers

---

.swiftlint.yml

This narrows the `trailing_closure` rule to apply only to single muted parameters (like `map(_:)`). This allows for using non-trailing closures in some cases where Xcode autocompletes them that way, like `first(where: { ... })` instead of `first { ... }`.

Relax trailing_closure rule

---

arcgis-ios-sdk-samples/Layers/Identify raster cell/README.metadata.json

Running style check script spotted this issue, which will cause the sample not rendering on website.

Fix: missing comma in Identify raster cell metadata json

---

arcgis-ios-sdk-samples/Analysis/Viewshed (location)/README.md
arcgis-ios-sdk-samples/Analysis/Viewshed (location)/README.metadata.json
arcgis-ios-sdk-samples/Display information/Simple marker symbol/README.md
arcgis-ios-sdk-samples/Layers/Dictionary renderer with feature layer/README.md
arcgis-ios-sdk-samples/Layers/Dictionary renderer with feature layer/README.metadata.json
arcgis-ios-sdk-samples/Maps/Set map spatial reference/README.md
arcgis-ios-sdk-samples/Maps/Set map spatial reference/README.metadata.json

A quick fix PR to remove redundant tags.
Discussed with our team and found out more duplicate API names that shouldn't go into tags. Removing them and running the check yields no error.

Fix: remove redundant tags

---

arcgis-ios-sdk-samples/Edit data/Offline edit and sync/README.metadata.json
arcgis-ios-sdk-samples/Route & Directions/Find closest facility to an incident (interactive)/README.metadata.json

ref: /runtime/common-samples/issues/2006
These 2 issues have been fixed in #888 on `philium/readme-updates` branch. However, in today's mtg, Mike suggested that they should be fixed ASAP as a hotfix on master branch, to avoid keeping looking bad until we merge the whole update.
Therefore, I made this hotfix to mitigate the issues in metadata, so that they can be fixed on developer site during the weekly build.

Hotfix: wrong category and duplicate entry on developer site

---

arcgis-ios-sdk-samples/Analysis/Statistical query (group and sort)/README.md
arcgis-ios-sdk-samples/Analysis/Viewshed (GeoElement)/README.md
arcgis-ios-sdk-samples/Edit data/Edit feature attachments/README.md
arcgis-ios-sdk-samples/Features/Feature layer query/README.md
arcgis-ios-sdk-samples/Features/Feature layer selection/README.md
arcgis-ios-sdk-samples/Geometry/List transformations/README.md
arcgis-ios-sdk-samples/Layers/Query a map image sublayer/README.md
arcgis-ios-sdk-samples/Layers/Raster layer (service)/README.md
arcgis-ios-sdk-samples/Layers/WMS layer (URL)/README.md
arcgis-ios-sdk-samples/Route & Directions/Offline routing/README.md
arcgis-ios-sdk-samples/Scenes/Scene layer (URL)/README.md
arcgis-ios-sdk-samples/Search/Find place/README.md

According to README style wiki, the section headers/sections should follow a certain order.
This PR fixes all the sections that are not in correct order in READMEs.
Reordering the sections and running the check yields no error.

Fix: reorder section headers

---

arcgis-ios-sdk-samples/Route & Directions/Find closest facility to an incident (interactive)/README.metadata.json

An issue causing the site not to render correctly. See image below

Hotfix: wrong category in metadata

---

arcgis-ios-sdk-samples/Augmented reality/Navigate in AR/NavigateARNavigatorViewController.swift
arcgis-ios-sdk-samples/Route & Directions/Navigate route/NavigateRouteViewController.swift

From the latest build of the SDK, a deprecation warning pops up:
```
'init(routeResult:routeIndex:)' is deprecated: Use 'initWithRouteResult:routeIndex:skipCoincidentStops:' instead
```
After reading the doc, I set `skipCoincidentStops` to true to fix this warning, as YES was the default value for this parameter.

Fix: deprecation warnings

---

arcgis-ios-sdk-samples/Edit data/Create and save KML file/CreateAndSaveKMLViewController.swift

This PR fixes the issue in `/runtime/common-samples/issues/2150`.
In the original implementation, when the save file `UIActivityViewController` is dismissed or completed, the KML file get deleted, without considering the case where user could cancel the process. This will cause the activity VC keep popping up when tapping on save files button again, as it cannot find the file with provided path.

Bugfix: Create save KML file deleted too early

---

arcgis-ios-sdk-samples/Scenes/Animate images with image overlay/AnimateImagesWithImageOverlay.storyboard
arcgis-ios-sdk-samples/Scenes/Animate images with image overlay/AnimateImagesWithImageOverlayViewController.swift

Description: The opacity slider is embedded in a `UIBarButtonItem`. Current version sets slider's `isEnabled` property to false in storyboard, which dims its tint color to indicate it is not interactive. After enabling it in code, the color does not update, which might give wrong clues to the user that the slider is not operable.
This fix invert the settings: enable in storyboard, and disable in code if loading images failed.
Please see the comparison images below.
|Before|After|
|-|-|
|![before](https://user-images.githubusercontent.com/9660181/89583939-1274f880-d7f0-11ea-82bc-6c37399e50f5.png)|![after](https://user-images.githubusercontent.com/9660181/89583938-11dc6200-d7f0-11ea-9067-2d34247c8a44.png)|
ref: #857

Fix: Animate images with image overlay slider color

---

arcgis-ios-sdk-samples.xcodeproj/project.pbxproj

In the project file there are a few files using wrong folder reference that set to "Relative to project" rather than the default "Relative to group". This PR fixes all the wrong paths.

Fix: Wrong folder references in project file

---

arcgis-ios-sdk-samples/Content Display Logic/Controllers/OptionsTableViewController.swift

Before | After
------ | -----
I've never been happy with how selection was implemented in `OptionsTableViewController`. The tapped cells are not highlighted as excepted and the selection change isn't animated. This PR addresses those issues by simply reloading the previously selected row and the newly selected row. Rows are now highlighted when tapped and both the highlight and the checkmark changes are animated.

Fix selection in OptionsTableViewController

---

arcgis-ios-sdk-samples/Content Display Logic/Controllers/OptionsTableViewController.swift

This PR updates `OptionsTableViewController` to support the absence of a selection by passing `nil` for the `selectedIndex`. It also prevents unnecessary work from being done when the currently selected row is tapped.

Update OptionsTableViewController to support no selection

---

arcgis-ios-sdk-samples/Content Display Logic/Controllers/Color Picker/ColorPickerViewController.swift

The issue appeared after upgrading to the newest version of SwiftLint.

Fix computed_accessors_order violation

---

arcgis-ios-sdk-samples.xcodeproj/project.pbxproj

By uncheck and check the auto-signing checkbox, Xcode wishes to make these changes. It seems to be introduced by Mac Catalyst support.
Please verify this is reproducible. 😳  I saw this change when I sign & archived the app to upload to AppStore. Probably it is a change wanted by Apple.

Update: changes to signing & capabilities in project file by Xcode

---

Scripts/download-portal-item-data.swift
arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
arcgis-ios-sdk-samples/Content Display Logic/PortalItems.plist
arcgis-ios-sdk-samples/Scenes/Animate images with image overlay/AnimateImagesWithImageOverlayViewController.swift
arcgis-ios-sdk-samples/Scenes/Animate images with image overlay/README.md

This PR fixes the issue in #857 (Animate images with image overlay) and #865 , where we decided to add "-j" flag to call `unzip` so that it omits all enclosing folders and extract files to a flattened directory. It also replaced the item that caused trouble.
Removing the flag means now extracting zip archive will preserve their folder structure, and we need to
- Add the folder tree as-is when introducing new item to the `Portal Data` folder
- (Negotiate with sample designer to) ensure future zip archives do not contain irrelevant hidden files or redundant folders

Update: remove -j flag from download script and fix portal item

---

.github/workflows/main.yml
Scripts/CI/README_Metadata_StyleCheck/Dockerfile
Scripts/CI/README_Metadata_StyleCheck/README_style_checker.py
Scripts/CI/README_Metadata_StyleCheck/action.yml
Scripts/CI/README_Metadata_StyleCheck/description_differ.py
Scripts/CI/README_Metadata_StyleCheck/entry.py
Scripts/CI/README_Metadata_StyleCheck/metadata_style_checker.py
Scripts/CI/README_Metadata_StyleCheck/style.rb
Scripts/CI/README_Metadata_StyleCheck/title_differ.py

This PR adds a set of scripts and 2 GitHub Actions workflow YAML files to `v.next` branch, to enforce styling for `README.md` and `README.metadata.json` files.
Steps to review:
1. (Optional) Read about the background in /common-samples/issues/2018
1. (Optional) Read about the GitHub Actions wiki in /common-samples/wiki/README-and-metadata-status-check-with-GitHub-Actions
1. Try it out to see how it works in my forked repo: https://github.com/yo1995/arcgis-runtime-samples-ios/pulls. 
I've set the repo up exactly the same as this PR. When you create a PR to `v.next` in that repo, it will run the checks and give success/failure status, and print error output into the console.
1. Review the files
- `main.yml` and `action.yml` are GitHub Actions configuration files
- `style.rb` is a …

CI: Add GitHub Actions workflow and style checking tools

---

arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
arcgis-ios-sdk-samples/AppDelegate.swift
arcgis-ios-sdk-samples/Assets.xcassets/Colors/AccentColor.colorset/Contents.json
arcgis-ios-sdk-samples/Assets.xcassets/Colors/statusLabelBackgroudColor.colorset/Contents.json
arcgis-ios-sdk-samples/Cloud and portal/Search for webmap by keyword/SearchForWebmapByKeywordViewController.swift
arcgis-ios-sdk-samples/Content Display Logic/Controllers/Color Picker/ColorPicker.storyboard
arcgis-ios-sdk-samples/Content Display Logic/Controllers/ContentCollectionViewController.swift
arcgis-ios-sdk-samples/Content Display Logic/Controllers/ListViewController.swift
arcgis-ios-sdk-samples/Content Display Logic/Controllers/SampleInfoViewController.swift
arcgis-ios-sdk-samples/Content Display Logic/Controllers/SourceCodeViewController.swift
arcgis-ios-sdk-samples/Content Display Logic/Js/darkmode.css
arcgis-ios-sdk-samples/Content Display Logic/Js/solarized-dark.css
arcgis-ios-sdk-samples/Content Display Logic/Storyboard/LaunchScreen.storyboard
arcgis-ios-sdk-samples/Content Display Logic/Storyboard/Main.storyboard
arcgis-ios-sdk-samples/Content Display Logic/Views/DownloadProgressView.swift
arcgis-ios-sdk-samples/Content Display Logic/Views/DownloadProgressView.xib
arcgis-ios-sdk-samples/Info.plist

This PR adapts or updates every color in Content Display Logic folder to Dark Mode. It includes
- Change colors in `Main.storyboard` for each custom color in view controllers
- Add a color to `AppDelegate.swift`
- Change color for color picker view controller
- Change colors for the search bar, which is used both in content collection view controller (the main screen card view) and in `SearchForWebmapByKeywordViewController.swift`
- Change CSS styles for README and source code panes, so that they are responsive to Dark Mode
- Update colors in download progress view - for on-demand resource dependent samples
You can use <kbd>command</kbd> + <kbd>shift</kbd> + <kbd>A</kbd> to toggle Dark Mode in Simulator.
Also, I removed the force Light Mode flag, so there is no need to edit anything when …

[Dark Mode] Update: Content Display Logic

---

arcgis-ios-sdk-samples/AppDelegate.swift

This fixes an issue where interactive elements in an alert controller (buttons, etc.) had the wrong tint color on iOS 14.

Fix alert controller tint color on iOS 14

---

arcgis-ios-sdk-samples/Info.plist

This PR fixes the Compliance warning on AppStore Connect so that next time the app is uploaded, it will automatically go into internal testing after processing is done.
|1|2|
|-|-|
|<img width="619" alt="compliance-1" src="https://user-images.githubusercontent.com/9660181/98273031-a9179980-1f46-11eb-8078-1a14b508a749.png">|<img width="817" alt="compliance-2" src="https://user-images.githubusercontent.com/9660181/98273024-a6b53f80-1f46-11eb-92ab-d676774d242b.png">|
When the app is uploaded to AppStore Connect, it won't immediately go into internal testing, but get stuck by the compliance warning. Since we are not using encrypted communication in our app, simply setting it to false will solve the problem. Read more at
- https://developer.apple.com/documentation/bundleresources/information_pr …

Fix: Change info.plist to fix compliance warning

---

arcgis-ios-sdk-samples/Maps/Generate offline map (overrides)/GenerateOfflineMapOverridesViewController.swift
arcgis-ios-sdk-samples/Maps/Generate offline map/GenerateOfflineMapViewController.swift

This PR removes the lines that change the title of the sample's main view controller.

Fix: Not to change the title of GenerateOfflineMap samples

---

Scripts/CI/README_Metadata_StyleCheck/style.rb
arcgis-ios-sdk-samples/Layers/ArcGIS vector tiled layer (custom style)/README.md

In https://github.com/Esri/arcgis-runtime-samples-ios/pull/981#issuecomment-731330696 the PR used 2-trailing-space line break that makes the check yield error status.
This PR adds a new rule to the markdownlint rules to make an exception for such cases. Details at https://github.com/Esri/arcgis-runtime-samples-ios/pull/981#issuecomment-731397411

Fix: Add markdownlint exception rule for trailing spaces in README

---

arcgis-ios-sdk-samples/Layers/ArcGIS vector tiled layer (custom style)/VectorTileCustomStyle.storyboard
arcgis-ios-sdk-samples/Search/Offline geocode/SanDiegoAddressesViewController.swift

This PR runs the following checks
- Check `calibratedRGB` in storyboard
```sh
find . \( -name '*.xib' -or -name '*.storyboard' \) \
-exec echo {} \;        \
-exec xmlstarlet sel -t \
-m "//color[@colorSpace='calibratedRGB']" -c . -n  {} \; > ~/Desktop/calibratedRGBColors.md
```
- Check button text color
```sh
find . \( -name '*.xib' -or -name '*.storyboard' \) \
-exec echo {} \;        \
-exec xmlstarlet sel -t \
-m "//button[@key='textColor']" -c . -n  {} \; > ~/Desktop/buttonText.md
```
- Check text color
```sh
find . \( -name '*.xib' -or -name '*.storyboard' \) \
-exec echo {} \;        \
-exec xmlstarlet sel -t \
-m "//color[@key='textColor']" -c . -n  {} \; > ~/Desktop/textColors.md
```
- Search for `.backgroundColor = ` in the project to get rid of redundant assignment
and spotted …

Update: Remaining Dark Mode issues

---

arcgis-ios-sdk-samples/Layers/Group layers/GroupLayersSectionView.xib

This issue was spotted by Sarat. The PR fixes the toggle that controls group visibility.
To review: build with `v.next` and this branch to see the difference.
|Before|After|
|-|-|
|![before](https://user-images.githubusercontent.com/9660181/100912256-16a2e100-3485-11eb-8ec7-b124db9ccba5.gif)|![after](https://user-images.githubusercontent.com/9660181/100912252-1571b400-3485-11eb-92a9-8c463bd81036.gif)|

Fix: Group layer grouped toggle

---

arcgis-ios-sdk-samples/Analysis/Statistical query/StatisticalQueryViewController.swift
arcgis-ios-sdk-samples/Analysis/Viewshed (geoprocessing)/ViewshedGeoprocessingViewController.swift
arcgis-ios-sdk-samples/Augmented reality/Navigate in AR/NavigateARRoutePlannerViewController.swift
arcgis-ios-sdk-samples/Augmented reality/View hidden infrastructure in AR/ViewHiddenInfrastructureARPipePlacingViewController.swift
arcgis-ios-sdk-samples/Display information/Add graphics with symbols/GraphicsWithSymbolsViewController.swift
arcgis-ios-sdk-samples/Edit data/Edit features with feature-linked annotation/EditFeaturesWithFeatureLinkedAnnotationViewController.swift
arcgis-ios-sdk-samples/Edit data/Edit with branch versioning/EditWithBranchVersioningViewController.swift
arcgis-ios-sdk-samples/Features/Feature layer (feature service)/FeatureLayerURLViewController.swift
arcgis-ios-sdk-samples/Features/Feature layer (geopackage)/FeatureLayerGPKGViewController.swift
arcgis-ios-sdk-samples/Features/Feature layer (shapefile)/FeatureLayerShapefileViewController.swift
arcgis-ios-sdk-samples/Geometry/List transformations/ListTransformationsViewController.swift
arcgis-ios-sdk-samples/Layers/Apply mosaic rule to rasters/ApplyMosaicRuleToRastersViewController.swift
arcgis-ios-sdk-samples/Layers/Display KML/DisplayKMLViewController.swift
arcgis-ios-sdk-samples/Layers/Display annotation/DisplayAnnotationViewController.swift
arcgis-ios-sdk-samples/Layers/Identify raster cell/IdentifyRasterCellViewController.swift
arcgis-ios-sdk-samples/Layers/OpenStreetMap layer/OpenStreetMapLayerViewController.swift
arcgis-ios-sdk-samples/Layers/Query a map image sublayer/QueryMapImageSublayerViewController.swift
arcgis-ios-sdk-samples/Layers/Raster layer (geopackage)/RasterLayerGPKGViewController.swift
arcgis-ios-sdk-samples/Layers/Symbolize shapefile/SymbolizeShapefileViewController.swift
arcgis-ios-sdk-samples/Layers/WMS layer (URL)/WMSLayerUsingURLViewController.swift
arcgis-ios-sdk-samples/Maps/Read a geopackage/ReadGeopackageViewController.swift
arcgis-ios-sdk-samples/Maps/Set initial map location/SetInitialMapLocationViewController.swift
arcgis-ios-sdk-samples/Maps/Show location history/LocationHistoryViewController.swift
arcgis-ios-sdk-samples/Route and directions/Find closest facility to an incident (interactive)/FindClosestFacilityInteractiveViewController.swift
arcgis-ios-sdk-samples/Route and directions/Find service area interactive/FindServiceAreaInteractiveViewController.swift
arcgis-ios-sdk-samples/Scenes/Terrain exaggeration/TerrainExaggerationViewController.swift
arcgis-ios-sdk-samples/Utility network/Display utility associations/DisplayUtilityAssociationsViewController.swift

This PR updates the basemap constructors to use the U10 new metered APIs.
---
The mapping between `levelOfDetail` and `scale` is copied from https://services.arcgisonline.com/arcgis/rest/services/World_Street_Map/MapServer
```swift
// From
let map = AGSMap(basemapType: .streets, latitude: 39.7294, longitude: -104.8319, levelOfDetail: 11)
// To
let map = AGSMap(basemapStyle: .arcGISStreets)
map.initialViewpoint = AGSViewpoint(latitude: 39.7294, longitude: -104.8319, scale: 288895.277144)
```
Below are the remaining changes that will lead to many-to-one basemap mappings. For example: previously we had `streetsVector` and `streets` types, but the new API only has `arcGISStreets`. So both are mapped to the same new API.
According to Mike: 
> the new metered basemaps only showcase the vector …

Update: Basemap constructors 2

---

arcgis-ios-sdk-samples/Maps/Create and save a map/CreateOptionsViewController.swift
arcgis-ios-sdk-samples/Maps/Create and save a map/CreateSaveMapViewController.swift
arcgis-ios-sdk-samples/Maps/Create and save a map/SaveAsViewController.swift

This PR updates the `Create save map` sample with the new basemap APIs.
Note: Since the new basemap constructors require either signing in with a Named User, or an API key, the array in the table is changed to hold `AGSBasemapStyle`s.
Also, it seems the Named User authentication is not working with this sample. Not sure why but maybe related to the OAuth used in this sample... 😳  So please use API key to verify the changes.

Update: Create save map

---

arcgis-ios-sdk-samples/Geometry/Spatial operations/README.md

Sarat spotted that the README doesn't read well for the `difference` spatial operation.
Difference actually means the part which geometry1 differs from geometry2, or let's say all of geometry1 except the overlapping part of geometry2.

Update: Spatial operations README

---

arcgis-ios-sdk-samples/Info.plist

See details at `cocoa/issues/10241`

Fix: Add plist item to fix a crash in popup attachments

---

arcgis-ios-sdk-samples/Augmented reality/Navigate in AR/NavigateARRoutePlannerViewController.swift
arcgis-ios-sdk-samples/Cloud and portal/Authenticate with OAuth/AuthenticateWithOAuthViewController.swift

This PR fixes the issue of
- common-samples/issues/1613
by removing credentials on deinit, the samples won't share credential cache;
~~by reset the presentation style to default, the OAuth webpage cannot be dismissed with iOS 13 interactive swipe (which hangs the auth process in an unknown state) on both iPhone and iPad~~ this will be fixed in the SDK

Fix: Remove credentials when leaving OAuth samples

---

arcgis-ios-sdk-samples/Analysis/Line of sight (geoelement)/LineOfSightGeoElement.storyboard
arcgis-ios-sdk-samples/Analysis/Line of sight (geoelement)/LineOfSightGeoElementViewController.swift
arcgis-ios-sdk-samples/Content Display Logic/Controllers/Color Picker/ColorPicker.storyboard
arcgis-ios-sdk-samples/Maps/Generate offline map (overrides)/OfflineMapParameterOverridesViewController.swift
arcgis-ios-sdk-samples/Scenes/Surface placements/SurfacePlacementsViewController.swift

This PR fixes the bug in `common-samples/issues/2148` - slider doesn't honor the default value set in storyboard, in iOS 14.
There is no official bug reporting thread found on Apple forum, but the same issue was spotted by other developers. See section 2 in this post: https://fahimfarook.medium.com/xcode-12-and-ios-14-developer-bugs-and-issues-ada35920a104
This issue only affects iOS 14.
Fixed by setting the slider's value to max in code
Fixed by setting the default value to the height of ESB
Fixed by setting the value to the half of min + max
- not changed, the expected behavior is set to 0 each time. Reset the values in storyboard.

[Fix] Slider default value bug in iOS 14

---

.swiftlint.yml
arcgis-ios-sdk-samples/Display information/Identify graphics/GOIdentifyViewController.swift
arcgis-ios-sdk-samples/Display information/Show legend/MILLegendTableViewController.swift
arcgis-ios-sdk-samples/Features/Feature collection layer/FeatureCollectionLayerViewController.swift
arcgis-ios-sdk-samples/Layers/Manage sublayers/ManageSublayersViewController.swift
arcgis-ios-sdk-samples/Maps/Generate offline map (overrides)/GenerateOfflineMapOverridesViewController.swift
arcgis-ios-sdk-samples/Maps/Generate offline map/GenerateOfflineMapViewController.swift
arcgis-ios-sdk-samples/Maps/Set map spatial reference/SetMapsSRViewController.swift

Enables the `trailing_whitespace` [rule](https://realm.github.io/SwiftLint/trailing_whitespace.html), but ignores it for blank lines to match Xcode's default style of not trimming trailing whitespace from whitespace only lines. Also addresses all violations using `swiftlint autocorrect`.

Enable trailing_whitespace linting rule

---

arcgis-ios-sdk-samples.xcodeproj/project.pbxproj

This PR fixes the issue in
- `runtime/common-samples/issues/2004`
- `runtime/devops/issues/823`
- #1024 
by adjusting the on-demand raster used in `Identify raster cell` (#866) from `Create Groups` to `Create Folder References`, since the resource files come as a whole zip archive.
- Do a fresh clone of the project from this [branch](https://github.com/Esri/arcgis-runtime-samples-ios/tree/Ting/Try-ReplaceRaster) and do a clean build. 
- On the first build, `v.next` will give an `Build input file cannot be found: '$SRCROOT/Portal Data/Archives/SA_EVI_8Day_03May20/SA_EVI_8Day_03May20.tif'` error. The following builds won't give error since no additional portal item is added.
- This branch won't give any error
The error is hard to replicate because it only happens on the very first build of …

Fix: Change reference to the raster used in raster cell sample to fix build error

---

README.md
arcgis-ios-sdk-samples/Augmented reality/Explore scenes in flyover AR/README.md
arcgis-ios-sdk-samples/Augmented reality/Navigate in AR/README.md
arcgis-ios-sdk-samples/Augmented reality/View hidden infrastructure in AR/README.md
arcgis-ios-sdk-samples/Display information/Custom dictionary style/README.md
arcgis-ios-sdk-samples/Features/Service feature table (cache)/README.md
arcgis-ios-sdk-samples/Features/Service feature table (manual cache)/README.md
arcgis-ios-sdk-samples/Features/Service feature table (no cache)/README.md
arcgis-ios-sdk-samples/Layers/Add ENC exchange set/README.md
arcgis-ios-sdk-samples/Layers/Export tiles/README.md
arcgis-ios-sdk-samples/Layers/OpenStreetMap layer/README.md
arcgis-ios-sdk-samples/Maps/Apply scheduled updates to preplanned map area/README.md
arcgis-ios-sdk-samples/Maps/Download preplanned map/README.md

Because of the launch of the new website, a few links that include `/guide/` lead to 404 errors. This PR updates those links. Please note that some of the old documentation is not on the new site so I couldn't find the new links and they had to be removed completely.

Fix: 404 links

---

arcgis-ios-sdk-samples/Maps/Generate offline map (overrides)/GenerateOfflineMapOverridesViewController.swift
arcgis-ios-sdk-samples/Maps/Generate offline map/GenerateOfflineMapViewController.swift
arcgis-ios-sdk-samples/Maps/Map loaded/MapLoadedViewController.swift
arcgis-ios-sdk-samples/Route and directions/Navigate route/NavigateRouteViewController.swift

This PR fixes the issue mentioned here: 
- https://github.com/Esri/arcgis-runtime-samples-ios/pull/1037#discussion_r584211266
- https://github.com/Esri/arcgis-runtime-samples-ios/pull/988#discussion_r516696201
to remove the redundant weak capture of self within already weak scope.
Here is a SO thread to read more on when and where to use `[weak self]` https://stackoverflow.com/a/41992442/14369688
I don't know if we should make these kind of changes, but since we spotted them in new sample PRs, I tend to fix all existing ones in the codebase, so that we don't get confused by the inconsistency when revisiting those samples. 😳

Fix: remove redundant weakly captured `self`

---

arcgis-ios-sdk-samples/Scenes/Terrain exaggeration/TerrainExaggerationViewController.swift

This PR fixes `common-samples/issues/2571` where we accidentally introduced a basemap constructor change to the scene.

Fix: Revert basemap change to the scene

---

arcgis-ios-sdk-samples/Layers/Identify KML features/IdentifyKMLFeaturesViewController.swift
arcgis-ios-sdk-samples/Layers/Identify KML features/README.md

This PR proposes a fix for `common-samples/issues/2542`. 
In recent updates, core introduced a condition to return an empty string for the balloons/KML nodes that doesn't have description or extended data. The data source in the `Identify KML features` doesn't provide a description for each significant weather condition, thus empty balloons are displayed in the callout.
If description is absent for a placemark, add a placeholder so that the content of the balloon can be displayed.
The fix is for U11, but adding the attribute doesn't conflict with U10, so it can go into `v.next`.
Please note: the sample can only be tested if the data source contains significant weather in the US. Also, the issue only appears in the recent U11 daily builds.
- Before: the popup for any feature in the map is …

Fix: Empty balloon for placemarks in Identify KML features

---

arcgis-ios-sdk-samples/Analysis/Viewshed (location)/ViewshedLocationViewController.swift
arcgis-ios-sdk-samples/Augmented reality/Collect data in AR/CollectDataAR.swift
arcgis-ios-sdk-samples/Content Display Logic/Cells/ContentTableCell.swift
arcgis-ios-sdk-samples/Maps/Show location history/LocationHistoryViewController.swift

Remove redundant type annotation for rule `redundant_type_annotation` of SwiftLint to get ready for a clean release.

Fix: Linter warnings

---

arcgis-ios-sdk-samples/Utility network/Create load report/CreateLoadReportViewController.swift
arcgis-ios-sdk-samples/Utility network/Create load report/README.md

There has been 1 additional UN sample `Create load report` added since we created #1026 . With the rolled out SS7, the `Create load report` sample doesn't work with the invalid URL anymore.
This PR fixes the issue with the new URL and credentials.

Update: Create load report, Utility network URL for sample server 7

---

arcgis-ios-sdk-samples/Content Display Logic/ContentPList.plist
arcgis-ios-sdk-samples/Edit data/Edit and sync features/EditAndSyncFeatures.storyboard
arcgis-ios-sdk-samples/Edit data/Edit and sync features/EditAndSyncFeaturesViewController.swift

This PR is a quick fix to address the AppStore feedback on the crash in `Edit and sync features` sample
- Add `SanFrancisco.tpk` on-demand resource into plist dependency
- Fix the features not showing issue when the feature layers are loaded
- Clear away some smelling code
The sample would need further refactor, but as we are catching up with a release, let's punt it into the future...
Astonishingly, the On-Demand Resource bug has been there since 2019, but we never caught it as we've never run ad-hoc test on the AppStore released version. 😨 Really hard to catch.

Fix: Various bugs in Edit and sync features

---

.github/workflows/main.yml
README.md

This PR updates the wording `master` to `main`, to reflect the change in the primary branch's name.
Please note: this change directly targets at the `main` branch. Later these same changes will be merged into `v.next`
Also, I'm cancelling the status check because it depends on the branch name being `master`. After it's been merged, everything should be back to normal. 🤞 
Refs:
- https://github.com/github/renaming#later-this-year
- common-samples/issues/2251

Update: master to main

---

arcgis-ios-sdk-samples/Geometry/Project/Project.storyboard
arcgis-ios-sdk-samples/Layers/Identify raster cell/IdentifyRasterCell.storyboard

In U10 when the callout isn't dark mode adaptive, we hardcoded the text color to black in 2 custom callout views. Now it is time to revert them as callout supports Dark Mode!

Update: callout custom view text color

---

arcgis-ios-sdk-samples/Utility network/Create load report/CreateLoadReportViewController.swift

After the Friday review meeting, Tanner and I collaborated to find out the issue within the code. And later we realized that it would be better to explicitly specify the result types for the trace, instead of relying on the default populated elements type.
Pros and cons for this change:
- Pros: the user can have a clearer expectation for the output result types
- Cons: it seems a bit redundant to override the default value, as it was described in the docstring
I find this change helpful because I didn't realize/took for granted that the element output type was implicitly included, without thinking about the reason.
Please let me know your thoughts!
---
This PR doesn't change the behavior of the sample.

Fix: Explicitly specify the result types for Create load report

---

arcgis-ios-sdk-samples/Augmented reality/Navigate in AR/NavigateARRoutePlannerViewController.swift
arcgis-ios-sdk-samples/Augmented reality/Navigate in AR/README.md

This PR resolves the issue in
- common-samples/issues/2678
- common-samples/issues/2677
that uses API key instead of OAuth to authenticate the user for the navigation task.

Update: Replace route API and remove OAuth from Navigate in AR

---

arcgis-ios-sdk-samples/Augmented reality/Navigate in AR/NavigateARNavigatorViewController.swift
arcgis-ios-sdk-samples/Route and directions/Navigate route with rerouting/NavigateRouteWithReroutingViewController.swift
arcgis-ios-sdk-samples/Route and directions/Navigate route/NavigateRouteViewController.swift

`common-samples/issues/2288`
User may use the route tracker sample code in the sample viewer. There are a few scenarios
- User is in developer mode without a license: the basemap will show the watermark, but all functionalities would work
- User uses a Advanced license string for deployment: all good
- User uses a Lite license string: in this case, since the route tracking is not supported by Lite license, the `AGSRouteTracker.trackLocation(_:completion:)` call would fail and give error. 
However in our (my 🤕 ) previous implementations, we didn't handle that error and let the sample fail silently. That is due to my negligence of others using Lite license to build the app. See more in #980 
Better depict with a table
||`v.next`|this branch|
|-|-|-|
|Dev mode|✅ no error|✅ no error|
|Lite|❌ …

Fix: Add alert for route tracker licensing error

---

arcgis-ios-sdk-samples/Maps/Show location history/LocationHistoryViewController.swift

Please refer to `common-samples/issues/2239` for more details.
Last year Simone from Java team noticed that
> I noticed that if you pan away from the location symbol, then pan back again, extra polylines are created on the tracking line.
It is due to that this sample reads the current location from the location display's `mapLocation`, i.e. the location of the blue indicator, and uses it to create the polyline. There was a pan momentum on the `mapView` which makes this position point not accurate enough, and causes overlapping polyline graphics.
A video before making the changes in this PR - see the polylines
https://user-images.githubusercontent.com/9660181/120567560-f5d12f00-c3c6-11eb-8a5d-bbd36e87bac6.mp4
One way to fix the issue is to pass the location update from …

Fix: location display overlapping issue in `Show location history`

---

Scripts/CI/README_Metadata_StyleCheck/metadata_style_checker.py

This PR adds the GIF extension to the checker script so that it doesn't give an error for https://github.com/Esri/arcgis-runtime-samples-ios/pull/1080 .

Update: Add GIF extension to the metadata checker script

---

arcgis-ios-sdk-samples.xcodeproj/project.pbxproj

Similar to #1069 
Note: 100.11.2 pre UC build of the sample viewer will be uploaded around July 2nd, next Friday. 
Before that, a TestFlight build will be rolled out. - done
I'll start to draft a release note/list of samples updated for 11.2 soon.

Update: 100.11.2 version number

---

arcgis-ios-sdk-samples/Maps/Generate offline map (overrides)/GenerateOfflineMapOverridesViewController.swift
arcgis-ios-sdk-samples/Maps/Generate offline map (overrides)/README.md
arcgis-ios-sdk-samples/Maps/Generate offline map/GenerateOfflineMapViewController.swift
arcgis-ios-sdk-samples/Maps/Generate offline map/README.md

Please refer to the Epic issue `common-samples/issues/2823`.
Per Trevor
> Several samples use a named user authentication pattern for simplicity, but it is now simpler to use an API key - especially with the API being set ubiquitously across most samples with the sample viewer.
Samples we should update:

Update: Replace/Remove OAuth with API key

---

arcgis-ios-sdk-samples/Edit data/Edit feature attachments/EditFeatureAttachmentsViewController.swift
arcgis-ios-sdk-samples/Edit data/Edit features (connected)/EditFeaturesOnlineViewController.swift

Please refer to `common-samples/issues/1527` for more details.
This PR
- Add 1 line to disable interactive swipe down on the attachment controller, so that it has to be dismissed via the "Done" button
- Re-indent the files
It would be better if you can help to test on both iPhone and iPad 😄

Fix: VC dismissal issue in `Edit feature attachments` and `Edit features (connected)`

---

Documentation/ConfigureAppSecrets.md
README.md
arcgis-ios-sdk-samples/AppDelegate.swift
arcgis-ios-sdk-samples/AppSecrets.swift.masque

Please see `common-samples/issues/2910` for the details. This PR aims to
- Get rid of the "uncomment a line in `AppDelegate`" step for daily development or archive
- Don't give `fatalError` if no API key or license key provided; instead make these keys optional
After these changes, the new behaviors...
- No key provided: login required, license watermark exists after successful ArcGIS Identity login
- API key provided: basemap can show, license watermark appear on the basemap
- License key provided: login required, license watermark disappear
- Both provided: normal as before, no watermark or login required
To Sarat: Please notice this change might slightly simplify your testing workflow. 🙂 
- Should I put the `Configure App Secrets` details in the wiki, or should I put it in …

Update: Change licensing method to facilitate development

---

arcgis-ios-sdk-samples/Layers/OpenStreetMap layer/OpenStreetMapLayerViewController.swift
arcgis-ios-sdk-samples/Layers/OpenStreetMap layer/README.md

Our "OpenStreetMap layer" sample uses an OSM basemap. The original intention of this sample was to actually demonstrate use of the `AGSOpenStreetMapLayer` class.
Please refer to...
- https://github.com/Esri/arcgis-runtime-samples-java/pull/663
- https://github.com/Esri/arcgis-runtime-samples-qt/pull/1301
- `common-samples/issues/2474`

Update: `OpenStreetMap layer`

---

arcgis-ios-sdk-samples/Layers/Identify raster cell/IdentifyRasterCellViewController.swift

This PR resolves an issue brought to my attention by Divesh. After launching the "Identify raster cell" sample, the data did not load properly and an error message said "File error". See `common-samples/3016` for more info.

Fix file error

---

arcgis-ios-sdk-samples/Maps/Map reference scale/MapReferenceScaleSettingsViewController.swift

Close #1108 Sample should work the same as before.

Fix: Remove redundant property in `Map reference scale`

---

arcgis-ios-sdk-samples/Info.plist

This PR removes the unused HTTP exception URLs for `Display KML network links` sample, which was added in #500 . Now that the dataset has been updated all URLs to HTTPS, these 2 can be removed.
Please see `common-samples/issues/3160` for details. I reviewed their `git blame` history and they seem to be solely used by this sample.
To double check this doesn't affect other samples, we can go through every KML sample to see if they are working fine. (but I really don't think that is necessary 😏 )

Update: Remove 2 unused exception HTTP URLs for `Display KML network links`

---

arcgis-ios-sdk-samples/Route and directions/Route around barriers/RouteAroundBarriersViewController.swift

This PR fixes `Route around barriers` in `Route and directions` category. The sample was first added in #150
`common-samples/issues/814`
Run the sample, and solve a route.
- The solved route graphic should be padded with a margin to the screen
- No warning message in the console
@philium when you have a chance, can you elaborate on the first 2 issues you mentioned in the original post?
I cannot figure out which part of sample code should be improved, or maybe they are already fixed in the SDK or core.
- Respond appropriately if the service is down. Just got this in the console.
I cannot repro this issue, so didn't add error handling.
- Runtime Error for some portions of the route
I'm not sure where does this come from either. 😳 
- Pad the portion of the route more as you display it
I …

Fix: `Route around barriers` misc issues

---

arcgis-ios-sdk-samples/Maps/Show device location using indoor positioning/ShowDeviceLocationUsingIndoorPositioningViewController.swift
arcgis-ios-sdk-samples/Shared resources/Extensions/AGSExtensions.swift

In recent 3450 build a few changes give compiler warnings. See `cocoa/pull/11033`.
Will merge this PR when everyone starts to use U14 dev SDK.

[Fix] Fix compiler warnings

---

arcgis-ios-sdk-samples/Layers/Group layers/GroupLayersSectionView.swift
arcgis-ios-sdk-samples/Maps/Display device location with NMEA data sources/DisplayDeviceLocationWithNMEADataSourcesViewController.swift

This PR fixes compiler warnings from the recent macOS 12.3 and Xcode 13.3 (Swift 5.6) update.
> Implicit use of 'self' in closure; use 'self.' to make capture semantics explicit; this is an error in Swift 6

[Fix] Swift 5.6 compiler warnings

---

arcgis-ios-sdk-samples/Edit data/Add features (feature service)/AddFeaturesViewController.swift
arcgis-ios-sdk-samples/Edit data/Delete features (feature service)/DeleteFeaturesViewController.swift
arcgis-ios-sdk-samples/Edit data/Update attributes (feature service)/UpdateAttributesOptionsViewController.swift
arcgis-ios-sdk-samples/Edit data/Update attributes (feature service)/UpdateAttributesViewController.swift
arcgis-ios-sdk-samples/Edit data/Update geometries (feature service)/EditGeometryViewController.swift

This PR replaces various usage of `applyEdits` method on `AGSServiceFeatureTable` to `AGSServiceGeodatabase`, to prevent data inconsistency issue.
I'll break down the Epic into 2 PRs to make it easier to review. This is the 1st PR.
All the behaviors should remain the same. Coding style has been updated/refactored to follow our latest style guide. Also, a few UI related bugs are fixed. But we'll still request Sarat's review to ensure nothing is breaking the tests.
Also, all comment strings are formatted.
Finally, READMEs will be updated in yet another separate PR, after we finish updating the common designs.
`common-samples/issues/3371`
Go though all changed samples and see if they work as expected.
<details><summary>Example change</summary>
```swift
/// Load and set a service geodatabase …
```

[Update] Replace instances of `AGSServiceFeatureTable.applyEdits` , 1st PR

---

arcgis-ios-sdk-samples/Augmented reality/View hidden infrastructure in AR/ViewHiddenInfrastructureARPipePlacingViewController.swift

This PR fixes compiler warning on LocationDataSource `stopWithCompletion`.
It was introduced in a recent daily build, around 3456 .
- `runtime/cocoa/pull/11040`

[Fix] Address compiler deprecation warning

---

arcgis-ios-sdk-samples/Analysis/Line of sight (geoelement)/LineOfSightGeoElementViewController.swift
arcgis-ios-sdk-samples/Augmented reality/Collect data in AR/CollectDataAR.swift
arcgis-ios-sdk-samples/Augmented reality/Explore scenes in flyover AR/ExploreScenesInFlyoverAR.swift
arcgis-ios-sdk-samples/Augmented reality/Navigate in AR/NavigateARNavigatorViewController.swift
arcgis-ios-sdk-samples/Augmented reality/View hidden infrastructure in AR/ViewHiddenInfrastructureARExplorerViewController.swift
arcgis-ios-sdk-samples/Layers/Display KML network links/DisplayKMLNetworkLinksViewController.swift
arcgis-ios-sdk-samples/Layers/List KML contents/ListKMLContentsSceneViewController.swift
arcgis-ios-sdk-samples/Scenes/Add a point scene layer/AddPointSceneLayerViewController.swift
arcgis-ios-sdk-samples/Scenes/Add an integrated mesh layer/AddIntegratedMeshLayerViewController.swift
arcgis-ios-sdk-samples/Scenes/Change atmosphere effect/ChangeAtmosphereEffectViewController.swift
arcgis-ios-sdk-samples/Scenes/Create terrain surface from a local raster/CreateTerrainSurfaceFromLocalRasterViewController.swift
arcgis-ios-sdk-samples/Scenes/Create terrain surface from a local tile package/CreateTerrainSurfaceFromLocalTilePackageViewController.swift
arcgis-ios-sdk-samples/Scenes/Feature layer extrusion/FeatureLayerExtrusionViewController.swift
arcgis-ios-sdk-samples/Scenes/Get elevation at a point/GetElevationPointViewController.swift
arcgis-ios-sdk-samples/Scenes/Sync map and scene views/SyncMapAndSceneViewsViewController.swift
arcgis-ios-sdk-samples/Scenes/View point cloud data offline/ViewPointCloudDataOfflineViewController.swift

This PR updates all `AGSScene` with the `AGSScene.init(basemapType:)` constructor to the latest `AGSScene.init(basemapStyle:)` due to
> BasemapType enum and associated constructor, as well as the factory Basemap methods have been deprecated at 100.14.
- `common-samples/issues/3436`
- `common-samples/issues/3267`
Run a few changed samples and see they should still work.
Sarat might need to run the basemap auto update script to use the latest basemapStyles that might contain subtle differences to the older basemaps.

[Update] AGSBasemapType enum have been deprecated at 100.14

---

README.md

This PR updates the app link on App Store. 
- When you click on https://itunes.apple.com/us/app/arcgis-runtime-sdk-for-ios/id1180714771 , it will auto redirect to https://apps.apple.com/us/app/arcgis-runtime-sdk-for-ios/id1180714771 , so I updates the former to the latter.

[Update] App Store app link

---

arcgis-ios-sdk-samples/Maps/Set max extent/SetMaxExtentViewController.swift

This PR fixes an issue in `Set max extent` in `Maps` category, see https://github.com/Esri/arcgis-runtime-samples-ios/pull/1167#discussion_r869577927

[Fix] `Set max extent`

---

arcgis-ios-sdk-samples/Augmented reality/Explore scenes in flyover AR/ExploreScenesInFlyoverAR.swift

This PR fixes a bug in `Explore sceneS in flyover AR` in `Augmented reality` category.
Branch: [URL_TO_BRANCH](https://github.com/Esri/arcgis-runtime-samples-ios/tree/Viv/fixFlyoverAR)
- `common-samples/issues/3492`
Launch sample, ensure that camera is not tilted.

Fix: Explore sceneS in flyover AR

---

arcgis-ios-sdk-samples/Scenes/Animate 3D graphic/Animate3DGraphicViewController.swift

This PR fixes a bug in `Animate 3D graphic` in `Scenes` category.
Branch: [URL_TO_BRANCH](https://github.com/Esri/arcgis-runtime-samples-ios/tree/Viv/fixAnimate3DGraphic)
- `common-samples/issues/3426`
Open the "stats" popup while the animation is playing and while it is paused. Ensure the correct stats are displayed while animation is playing and paused.

Fix: Animate 3D graphic

---

arcgis-ios-sdk-samples/Cloud and portal/Authenticate with OAuth/AuthenticateWithOAuthViewController.swift
arcgis-ios-sdk-samples/Cloud and portal/Token authentication/TokenAuthenticationViewController.swift

This PR fixes `Token Authentication` in `Cloud and Portal` category.
Branch: [URL_TO_BRANCH](https://github.com/Esri/arcgis-runtime-samples-ios/tree/Viv/fixAuthenticateOAuth)
- `common-samples/issues/3491`
First open the `Authenticate with OAuth` sample, log in, then open the `Token Authentication` sample. Ensure that you're prompted to log in upon `Token Authentication` launching.
Although this fixes the problem, it may not be the best solution because it deviates from the token authentication workflow and best practices. Additionally, it's redundant since the credential cache is cleared twice.

Fix: Authenticate with OAuth bug

---

arcgis-ios-sdk-samples/Content Display Logic/Controllers/CategoryTableViewController.swift

This PR resolves the issue Ting found [here](https://github.com/Esri/arcgis-runtime-samples-ios/pull/1175#discussion_r896158415).
- `common-samples/issues/3603`
Tap on the accessory buttons next to the sample titles to confirm that the app doesn't crash.

Fix: Info button bug

---

arcgis-ios-sdk-samples/Layers/Identify KML features/IdentifyKMLFeaturesViewController.swift

This PR implements `Identify KML features` in `Layers` category.
Branch: [URL_TO_BRANCH](https://github.com/Esri/arcgis-runtime-samples-ios/tree/Viv/fixIdentifyKML)
- `common-samples/issues/946`
Tap on the features and ensure that the popup displays more accurately to the location of the tapped point.

Fix: Identify KML features tolerance

---

arcgis-ios-sdk-samples/Maps/Show device location using indoor positioning/README.md
arcgis-ios-sdk-samples/Maps/Show device location using indoor positioning/ShowDeviceLocationUsingIndoorPositioningViewController.swift

This PR replaces the indoor map with a publicly accessible alternative.
- `common-samples/pull/3676`
Ting will go into Building L to test. Other than that, open the sample and see if the map can load.
Please note:
- transmitter count shows 0
- positioning source shows AppleIPS instead of Bluetooth
I reported these issues in #indoor-positioning-questions channel and am waiting for response.

[Update] Replace with a publicly accessible indoor map

---

arcgis-ios-sdk-samples.xcodeproj/project.pbxproj

This PR fixes more build warnings provided by Xcode 14 beta 4. The nature of the warnings are similar to Swift SV pull 41.
```
Run script build phase 'Run Script' will be run during every build because it does not specify any outputs. To address this warning, either add output dependencies to the script phase, or configure it to run in every build by unchecking "Based on dependency analysis" in the script phase.
```
See similar issue here: https://github.com/realm/SwiftLint/issues/4015

[Fix] Address Xcode 14 build warnings

---

arcgis-ios-sdk-samples/Features/Feature layer selection/FeatureLayerSelectionViewController.swift
arcgis-ios-sdk-samples/Features/Feature layer selection/README.md

This PR changes the data reference in `Feature layer selection` in `Features` category.
- It updates the README to use the GDP per capita data, rather than the GDP total data
- It also uses the portal item instead of the raw feature service to create the feature layer
- `common-samples/issues/3598`
Related links
- https://www.arcgis.com/home/item.html?id=10d76a5b015647279b165f3a64c2524f
- https://www.arcgis.com/home/item.html?id=0c4b6b70a56b40b08c5b0420c570a6ac
- https://services1.arcgis.com/4yjifSiIG17X0gW4/arcgis/rest/services/GDP_per_capita_1960_2016/FeatureServer/0
No visual changes. Verify the sample is the same as before.

[Fix] Change data reference in `Feature layer selection`

---

arcgis-ios-sdk-samples/Features/Filter by definition expression or display filter/README.md
arcgis-ios-sdk-samples/Features/Filter by definition expression or display filter/README.metadata.json

This PR removes "AGSDefinitionExpression" from metadata json as it is not a valid API name. Thanks @TADraeseke for spotting this.

[Fix] Remove wrong API name

---

arcgis-ios-sdk-samples/Route and directions/Navigate route with rerouting/NavigateRouteWithReroutingViewController.swift

This PR makes a further fix to #1191 . Since the rerouting sample requires the network data, it's unknown why it cannot be accessed by the other route task initializer. It is probably because the ODR isn't in that initializer's search paths.
- `common-samples/issues/3734`
Upload another TestFlight build to test. Current build 20220804 still gives error.

[Fix] San Diego network data on-demand resource access

---

README.md
arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
podfile

This PR bumps version number for U15, getting ready for release. Prev -> #1163 
Please notice: this PR contains a change that requires U15 iOS Swift package https://github.com/Esri/arcgis-runtime-ios, which hasn't been released yet, so it will show a build error if you build now.

[Update] Bump version number for U15
