Esri/arcgis-runtime-samples-ios

- README.md
Including Swift in the metadata to be parsed by http://esri.github.io
@dg0yal Please verify
> Updated the README.md to include swift

- OfflineFeatureEditingSample/swift/OfflineFeatureEditing/Base.lproj/Main.storyboard
- OfflineFeatureEditingSample/swift/OfflineFeatureEditing/FeatureTemplatePickerViewController.swift
- OfflineFeatureEditingSample/swift/OfflineFeatureEditing/ViewController.swift
made the Xcode 6.1.1 changes for tableview cell
removed the "Title" from templateVC
> #85 updated the name of the storyboard in the code

- arcgis-ios-sdk-samples/Maps/Display a map/DisplayMapViewController.swift
- arcgis-ios-sdk-samples/Maps/Display device location/README.md
Updated 2 files. Correct Copyright and updated Note in ReadMe.
> Updated copyright and readme.

- arcgis-ios-sdk-samples/Info.plist
@singhgag Please review
Based on the changes in iOS 9 specified here - https://developer.apple.com/library/prerelease/ios/technotes/App-Transport-Security-Technote/
> iOS9 security transport exceptions

- README.md
Updated the Xcode version support for Quartz beta.
> Update Xcode version support

- arcgis-ios-sdk-samples/Display information/Identify graphics/GOIdentifyViewController.swift
- arcgis-ios-sdk-samples/Display information/Show legend/MILLegendTableViewController.swift
- arcgis-ios-sdk-samples/Edit data/Delete features (feature service)/DeleteFeaturesViewController.swift
- arcgis-ios-sdk-samples/Edit data/Edit Features (connected)/EditFeaturesOnlineViewController.swift
- arcgis-ios-sdk-samples/Edit data/Edit feature attachments/EditAttachmentViewController.swift
- arcgis-ios-sdk-samples/Edit data/Update attributes (feature service)/EditAttributesViewController.swift
- arcgis-ios-sdk-samples/Edit data/Update geometries (feature service)/EditGeometryViewController.swift
- arcgis-ios-sdk-samples/Maps/Map rotation/MapRotationViewController.swift
- arcgis-ios-sdk-samples/Search/Find address/FindAddressViewController.swift
- arcgis-ios-sdk-samples/Search/Find place/FindPlaceViewController.swift
- arcgis-ios-sdk-samples/Search/Offline geocode/OfflineGeocodeViewController.swift
@singhgag Please review and merge
> Update to build 1260

- arcgis-ios-sdk-samples/Display information/Identify graphics/GOIdentifyViewController.swift
- arcgis-ios-sdk-samples/Display information/Show legend/MILLegendTableViewController.swift
- arcgis-ios-sdk-samples/Edit data/Delete features (feature service)/DeleteFeaturesViewController.swift
- arcgis-ios-sdk-samples/Edit data/Edit Features (connected)/EditFeaturesOnlineViewController.swift
- arcgis-ios-sdk-samples/Edit data/Edit feature attachments/EditAttachmentViewController.swift
- arcgis-ios-sdk-samples/Edit data/Update attributes (feature service)/EditAttributesViewController.swift
- arcgis-ios-sdk-samples/Edit data/Update geometries (feature service)/EditGeometryViewController.swift
- arcgis-ios-sdk-samples/Maps/Map rotation/MapRotationViewController.swift
- arcgis-ios-sdk-samples/Search/Find address/FindAddressViewController.swift
- arcgis-ios-sdk-samples/Search/Find place/FindPlaceViewController.swift
- arcgis-ios-sdk-samples/Search/Offline geocode/OfflineGeocodeViewController.swift
For offline geocoding sample while reverse geocoding on tap-hold-and-move.
> Remove flashing of callout

- arcgis-ios-sdk-samples/Layers/Vector tile layer/VectorTileLayerViewController.swift
> updating urls to use portal item url format

- README.md
- arcgis-ios-sdk-samples/Content Display Logic/Controllers/ContentTableViewController.swift
- arcgis-ios-sdk-samples/Content Display Logic/Custom BarButtonItem/SourceCodeBarButtonItem.swift
- arcgis-ios-sdk-samples/Display information/Sketch on the map/SketchViewController.swift
- arcgis-ios-sdk-samples/Edit data/Edit features (connected)/EditFeaturesOnlineViewController.swift
- arcgis-ios-sdk-samples/Edit data/Offline edit and sync/OfflineEditingViewController.swift
- arcgis-ios-sdk-samples/Layers/Change sublayer visibility/SublayersTableViewController.swift
- arcgis-ios-sdk-samples/Maps/Display device location/CustomContextSheet.swift
- arcgis-ios-sdk-samples/Maps/Take screenshot/MapViewScreenshotViewController.swift
- arcgis-ios-sdk-samples/Search/Find address/FindAddressViewController.swift
- arcgis-ios-sdk-samples/Search/Find place/FindPlaceViewController.swift
- arcgis-ios-sdk-samples/Search/Offline geocode/OfflineGeocodeViewController.swift
- selector changes
- readme update
> Swift 2.2 update

- arcgis-ios-sdk-samples/Edit data/Offline edit and sync/OfflineEditingViewController.swift
- arcgis-ios-sdk-samples/Features/Generate geodatabase/GenerateGeodatabaseViewController.swift
> Changes due to Info objects not being remote resource anymore.

- arcgis-ios-sdk-samples/Info.plist
AGOL supports the latest ciphers already.
> removed relaxation of TLS forward secrecy. 

- LicenseByOrgAccountSample/swift/LicenseByOrgAccount/Helper/LicenseHelper.swift
- OAuth Login Sample/README.md
- OAuth Login Sample/objective-c/OAuthLoginSample/Controllers/SignInViewController.m
- OAuth Login Sample/swift/OAuthLogin/Controllers/SignInViewController.swift
> use proper capitalization of OAuth

- arcgis-ios-sdk-samples/Edit data/Edit feature attachments/AttachmentsListViewController.swift
- arcgis-ios-sdk-samples/Edit data/Update attributes (feature service)/EditAttributesViewController.swift
- arcgis-ios-sdk-samples/Edit data/Update geometries (feature service)/EditGeometryViewController.swift
- arcgis-ios-sdk-samples/Features/Service feature table (manual cache)/ManualCacheViewController.swift
- arcgis-ios-sdk-samples/Search/Find address/FindAddressViewController.swift
- arcgis-ios-sdk-samples/Search/Find place/FindPlaceViewController.swift
- arcgis-ios-sdk-samples/Search/Offline geocode/OfflineGeocodeViewController.swift
- arcgis-ios-sdk-samples/Search/Reverse geocode/ReverseGeocodeViewController.swift
- removed unnecessary load calls
> Changes based on Loadable behavior changes

- arcgis-ios-sdk-samples/Display information/Sketch on the map/SketchViewController.swift
- arcgis-ios-sdk-samples/Edit data/Edit features (connected)/EditFeaturesOnlineViewController.swift
- arcgis-ios-sdk-samples/Edit data/Offline edit and sync/OfflineEditingViewController.swift
- arcgis-ios-sdk-samples/Edit data/Update geometries (feature service)/EditGeometryViewController.swift
> Updates based on phase 1 of sketch overlay design changes

- arcgis-ios-sdk-samples/Display information/Identify graphics/GOIdentifyViewController.swift
- arcgis-ios-sdk-samples/Display information/Show callout/CalloutViewController.swift
- arcgis-ios-sdk-samples/Edit data/Add features (feature service)/AddFeaturesViewController.swift
- arcgis-ios-sdk-samples/Edit data/Delete features (feature service)/DeleteFeaturesViewController.swift
- arcgis-ios-sdk-samples/Edit data/Edit feature attachments/EditAttachmentViewController.swift
- arcgis-ios-sdk-samples/Edit data/Edit features (connected)/EditFeaturesOnlineViewController.swift
- arcgis-ios-sdk-samples/Edit data/Offline edit and sync/OfflineEditingViewController.swift
- arcgis-ios-sdk-samples/Edit data/Update attributes (feature service)/EditAttributesViewController.swift
- arcgis-ios-sdk-samples/Edit data/Update geometries (feature service)/EditGeometryViewController.swift
- arcgis-ios-sdk-samples/Features/Feature layer selection/FLSelectionViewController.swift
- arcgis-ios-sdk-samples/Maps/Identify layers/IdentifyLayersViewController.swift
- arcgis-ios-sdk-samples/Maps/Mobile map (search and route)/MobileMapViewController.swift
- arcgis-ios-sdk-samples/Route & Navigation/Offline routing/OfflineRoutingViewController.swift
- arcgis-ios-sdk-samples/Route & Navigation/Route around barriers/RouteAroundBarriersViewController.swift
- arcgis-ios-sdk-samples/Search/Find address/FindAddressViewController.swift
- arcgis-ios-sdk-samples/Search/Find place/FindPlaceViewController.swift
- arcgis-ios-sdk-samples/Search/Offline geocode/OfflineGeocodeViewController.swift
- arcgis-ios-sdk-samples/Search/Reverse geocode/ReverseGeocodeViewController.swift
- AGSMapViewTouchDelegate not longer exists
- For all delegate methods changed mapView to geoView
> Touch delegate changes

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- arcgis-ios-sdk-samples/Content Display Logic/ContentPList.plist
- arcgis-ios-sdk-samples/Layers/ArcGIS vector tiled layer (custom style)/README.md
- arcgis-ios-sdk-samples/Layers/ArcGIS vector tiled layer (custom style)/VectorStylesViewController.swift
- arcgis-ios-sdk-samples/Layers/ArcGIS vector tiled layer (custom style)/VectorTileCustomStyle.storyboard
- arcgis-ios-sdk-samples/Layers/ArcGIS vector tiled layer (custom style)/VectorTileCustomStyleVC.swift
- ArcGIS vector tiled layer (custom style)
> Added new sample

- LicenseByOrgAccountSample/objective-c/Classes/AppDelegate.h
- LicenseByOrgAccountSample/objective-c/Classes/AppDelegate.m
- LicenseByOrgAccountSample/objective-c/Classes/ViewController.m
- LicenseByOrgAccountSample/objective-c/LicenseByOrgAccountSample.xcodeproj/project.pbxproj
- LicenseByOrgAccountSample/objective-c/LicenseByOrgAccountSample/Images.xcassets/AppIcon.appiconset/Contents.json
- LicenseByOrgAccountSample/objective-c/LicenseByOrgAccountSample/LicenseByOrgAccountSample.entitlements
- LicenseByOrgAccountSample/objective-c/LicenseHelper.h
- LicenseByOrgAccountSample/objective-c/LicenseHelper.m
- LicenseByOrgAccountSample/objective-c/LicenseHelperConstants.h
> License sample changes to Quartz

- arcgis-ios-sdk-samples/Scenes/Distance Composite Symbol/DistanceCompositeSymbolViewController.swift
- Increased the scale of model symbol
- Increased the size of the cone symbol
- changed the range of the composite symbol
> Scale changes mostly

- arcgis-ios-sdk-samples/Maps/Map rotation/MapRotation.storyboard
- arcgis-ios-sdk-samples/Scenes/Terrain exaggeration/TerrainExaggeration.storyboard
So setting a width on bbi and intrinsic height based on content
> The barbuttonItem seem to be expecting intrinsic size in iOS 11

- arcgis-ios-sdk-samples/Scenes/Extrude graphics/ExtrudeGraphicsViewController.swift
Reverts Esri/arcgis-runtime-samples-ios#299
> Revert "Removed unnecessary roll"

- arcgis-ios-sdk-samples/Layers/WMTS layer/WMTSLayerViewController.swift
Using SVProgressHUD to display error message instead of printing the error console.
> Using SVProgressHUD to display error message

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- arcgis-ios-sdk-samples/Features/Time based query/TimeBasedQuery.storyboard
- arcgis-ios-sdk-samples/Features/Time based query/TimeBasedQueryVC.swift
add files to project after resolving conflicts
@dg0yal please review. the other PR was merged before I could add my files back to project
> New Sample: Time based query (2)

- arcgis-ios-sdk-samples/Base.lproj/LaunchScreen.xib
Undoing https://github.com/Esri/arcgis-runtime-samples-ios/pull/311
> Revert copyright year.

- arcgis-ios-sdk-samples/Content Display Logic/ContentPList.plist
- arcgis-ios-sdk-samples/Layers/WMS layer (URL)/README.md
Made changes to `ContentPList` and `README` for `WMS layer (URL)` sample per sample design reference page.
> Change WMS layer sample doc

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- arcgis-ios-sdk-samples/Analysis/Viewshed (location)/ViewshedLocation.storyboard
- arcgis-ios-sdk-samples/Analysis/Viewshed (location)/ViewshedLocationViewController.swift
Use safearea for iPhone X compatibility.
Set the alpha on selected colors to 0.5 for viewshed `visibleAreaColor` and `obstructedColor`.
> Update Viewshed (location) sample

- arcgis-ios-sdk-samples/Analysis/Line of sight (location)/LineOfSightLocationViewController.swift
To incorporate feedback of @saratchandrakarumuri
> Update copyright in line of sight (location) sample

- arcgis-ios-sdk-samples/Analysis/Viewshed (location)/ViewshedLocation.storyboard
- arcgis-ios-sdk-samples/Analysis/Viewshed (location)/ViewshedLocationViewController.swift
Restructured to work with iOS 10.
@njarecha Could you confirm that this fixes the issue you were seeing please?
> Viewshed location popover display ios10 compatibility

- arcgis-ios-sdk-samples/Content Display Logic/Controllers/ContentCollectionViewController.swift
@dg0yal please review 
cc: @saratchandrakarumuri
> fix issue that resulted in white space above ContainerView in iOS 10.x

- arcgis-ios-sdk-samples/Content Display Logic/Storyboard/Main.storyboard
Fixes an issue where the source code view underlaid the navigation bar on iOS 10.
> Fixes source code view on iOS 10

- arcgis-ios-sdk-samples/Maps/Mobile map (search and route)/MapPackagesListViewController.swift
- arcgis-ios-sdk-samples/Maps/Mobile map (search and route)/MobileMapSearchRoute.storyboard
Fixes an issue where the map packages list view underlaid the navigation bar on iOS 10.
> Fixes map packages list view on iOS 10

- arcgis-ios-sdk-samples/Shared resources/Libraries/HorizontalPicker/HorizontalColorPicker.swift
> HorizontalColorPicker: Fixes animation when selected color changes

- arcgis-ios-sdk-samples/Cloud & Portal/List portal group users/GroupUsersViewController.swift
- arcgis-ios-sdk-samples/Content Display Logic/Controllers/ListViewController.swift
- arcgis-ios-sdk-samples/Content Display Logic/Views/CustomSearchHeaderView.swift
- arcgis-ios-sdk-samples/Edit data/Edit feature attachments/AttachmentsListViewController.swift
- arcgis-ios-sdk-samples/Edit data/Edit features (connected)/FeatureTemplatePickerViewController.swift
- arcgis-ios-sdk-samples/Edit data/Offline edit and sync/FeatureLayersViewController.swift
- arcgis-ios-sdk-samples/Edit data/Update attributes (feature service)/EAOptionsViewController.swift
- arcgis-ios-sdk-samples/Features/Add delete related features/RelatedFeaturesViewController.swift
- arcgis-ios-sdk-samples/Features/List related features/RelatedFeaturesListVC.swift
- arcgis-ios-sdk-samples/Geometry/Spatial operations/OperationsListViewController.swift
- arcgis-ios-sdk-samples/Layers/ArcGIS tiled layer (tile cache)/TilePackagesListViewController.swift
- arcgis-ios-sdk-samples/Layers/ArcGIS vector tiled layer (custom style)/VectorStylesViewController.swift
- arcgis-ios-sdk-samples/Layers/Change sublayer visibility/SublayersTableViewController.swift
- arcgis-ios-sdk-samples/Layers/Manage sublayers/MapImageSublayersVC.swift
- arcgis-ios-sdk-samples/Layers/RGB renderer/RGBRendererSettingsVC.swift
- arcgis-ios-sdk-samples/Layers/Stretch renderer/StretchRendererSettingsVC.swift
- arcgis-ios-sdk-samples/Maps/Change basemap/SwitchBasemapViewController.swift
- arcgis-ios-sdk-samples/Maps/Create and save a map/CreateOptionsViewController.swift
- arcgis-ios-sdk-samples/Maps/Display layer view state/LayerStatusViewController.swift
- arcgis-ios-sdk-samples/Maps/Manage bookmarks/BookmarksListViewController.swift
- arcgis-ios-sdk-samples/Maps/Manage operational layers/MMLLayersViewController.swift
- arcgis-ios-sdk-samples/Maps/Mobile map (search and route)/MapPackagesListViewController.swift
- arcgis-ios-sdk-samples/Maps/Open an existing map/OpenExistingMapViewController.swift
- arcgis-ios-sdk-samples/Route & Directions/Find route/DirectionsViewController.swift
- arcgis-ios-sdk-samples/Route & Directions/Route around barriers/DirectionsListViewController.swift
- arcgis-ios-sdk-samples/Search/Find address/WorldAddressesViewController.swift
- arcgis-ios-sdk-samples/Search/Find place/FindPlaceViewController.swift
- arcgis-ios-sdk-samples/Search/Offline geocode/SanDiegoAddressesViewController.swift
- arcgis-ios-sdk-samples/Shared resources/Libraries/ExpandableTableViewController/ExpandableTableViewController.swift
This prevents a force cast in most cases.
> Uses newer API to dequeue table view cells

- arcgis-ios-sdk-samples/Maps/Display drawing status/MapViewDrawStatusViewController.swift
This also fixes an issue where the draw status wasn't being displayed properly when the view first appears.
> Makes MapViewDrawStatusViewController update UI on main thread.

- arcgis-ios-sdk-samples/Edit data/Edit features (connected)/EditFeaturesOnline.storyboard
- arcgis-ios-sdk-samples/Edit data/Edit features (connected)/EditFeaturesOnlineViewController.swift
- arcgis-ios-sdk-samples/Edit data/Edit features (connected)/FeatureTemplatePickerViewController.swift
Among other things. It was too tempting to refactor the picker view controller into a subclass of `UITableViewController` while I was at it.
> Fixes crash in FeatureTemplatePickerViewController

- README.md
I also fixed the capitalization of Xcode.
> Updates readme with requirement of ArcGIS 100.3.0

- arcgis-ios-sdk-samples/Analysis/Viewshed (location)/ViewshedLocation.storyboard
- arcgis-ios-sdk-samples/Analysis/Viewshed (location)/ViewshedLocationViewController.swift
Previously the settings would be reset everytime the dialogue was opened, not showing accurate values for each setting.
> Makes viewshed location settings persist while in the sample.

- arcgis-ios-sdk-samples/Scenes/Terrain exaggeration/TerrainExaggeration.storyboard
- arcgis-ios-sdk-samples/Scenes/Terrain exaggeration/TerrainExaggerationViewController.swift
This matches the name style of all other samples.
> Renames ViewController to TerrainExaggerationViewController

- arcgis-ios-sdk-samples/Analysis/Line of sight (geoelement)/LineOfSightGeoElementViewController.swift
Match macOS sample with MeasurementFormatter.
> Update Line of Sight (GeoElement) 

- arcgis-ios-sdk-samples/Maps/Display drawing status/MapViewDrawStatusViewController.swift
I thought for sure this was only available on iOS 11, but I was wrong. Sweet!
> Use new KVO API for Draw Status sample

- arcgis-ios-sdk-samples/Maps/Generate offline map/GenerateOfflineMapViewController.swift
- arcgis-ios-sdk-samples/Maps/Generate offline map/README.md
Also updates the readme with further information.
> Generate Offline Map: Adds alert when individual layers have errors

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
As opposed to the ArcGIS static library packaged to look like a framework. This prevents us from having to pull in the resources bundle separately.
> Uses the ArcGIS framework

- arcgis-ios-sdk-samples/Scenes/Surface placements/SurfacePlacementsViewController.swift
Refactors sample to be more straightforward and adds documentation comments.
This is the counterpart to https://github.com/Esri/arcgis-runtime-samples-macos/pull/142.
> Cleans up SurfacePlacementsViewController.

- arcgis-ios-sdk-samples/Content Display Logic/Controllers/ContentCollectionViewController.swift
- arcgis-ios-sdk-samples/Content Display Logic/Controllers/ContentTableViewController.swift
- arcgis-ios-sdk-samples/Edit data/Offline edit and sync/OfflineEditingViewController.swift
- arcgis-ios-sdk-samples/Features/Add delete related features/AddDeleteRelatedFeaturesVC.swift
- arcgis-ios-sdk-samples/Features/Generate geodatabase/GenerateGeodatabaseViewController.swift
- arcgis-ios-sdk-samples/Maps/Change map view background/ChangeMapViewBackgroundVC.swift
- arcgis-ios-sdk-samples/Maps/Change viewpoint/SetViewpointViewController.swift
- arcgis-ios-sdk-samples/Maps/Create and save a map/CreateSaveMapViewController.swift
- arcgis-ios-sdk-samples/Route & Directions/Route around barriers/RouteAroundBarriersViewController.swift
- arcgis-ios-sdk-samples/Shared resources/Libraries/DemoTouchView/DemoTouchView.swift
These changes are backwards compatable with Xcode 9.4.
> Fixes build warnings generated when building in Xcode 10.

- arcgis-ios-sdk-samples/Analysis/Statistical query (group and sort)/StatisticalQueryGroupAndSortViewController.swift
- arcgis-ios-sdk-samples/Maps/Manage bookmarks/BookmarksViewController.swift
These changes are backwards compatible with Xcode 9.
> Fixes warnings when building in Xcode 10

- arcgis-ios-sdk-samples/Maps/Generate offline map/GenerateOfflineMapViewController.swift
> Generate Offline Map: Fixes typo

- arcgis-ios-sdk-samples/Features/Feature layer query/FLQueryViewController.swift
- arcgis-ios-sdk-samples/Features/Feature layer selection/FLSelectionViewController.swift
- arcgis-ios-sdk-samples/Features/List related features/ListRelatedFeaturesVC.swift
- arcgis-ios-sdk-samples/Geometry/Spatial relationships/SpatialRelationshipsViewController.swift
The new API endpoints are present but the functionality does not appear to be implemented yet. Still creating a PR for the initial implementation
> Replaces old selection properties API calls with new API calls

- arcgis-ios-sdk-samples/Maps/Open map (URL)/OpenMapURLViewController.swift
Also defaults the table selection to the default map in the same sample
> Allows the user to re-select the first sample in the open map (URL) sample

- arcgis-ios-sdk-samples/Content Display Logic/Controllers/ContentTableViewController.swift
Stuff I should have noticed in https://github.com/Esri/arcgis-runtime-samples-ios/pull/480
> Fix some SearchBar code

- arcgis-ios-sdk-samples/Scenes/Scene symbols/SceneSymbolsViewController.swift
This started out as an effort to use the new random API in Swift 4.2.
> Cleans up SceneSymbolsViewController

- arcgis-ios-sdk-samples/Content Display Logic/Controllers/ContentCollectionViewController.swift
- arcgis-ios-sdk-samples/Content Display Logic/Storyboard/Main.storyboard
> Keeps collection view cells inside the safe area

- arcgis-ios-sdk-samples/Base.lproj/LaunchScreen.xib
This replaces the text of the default launch screen and better aligns the app with the [iOS Human Interface Guidelines](https://developer.apple.com/design/human-interface-guidelines/ios/icons-and-images/launch-screen/).
> Redesigns the launch screen to mimic the UI of the first screen

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
This change was automatically recommended by Xcode.
> Fixes project file indentation

- arcgis-ios-sdk-samples/Layers/Change sublayer visibility/SublayerVisibility.storyboard
- arcgis-ios-sdk-samples/Layers/Change sublayer visibility/SublayerVisibilityViewController.swift
- arcgis-ios-sdk-samples/Layers/Change sublayer visibility/SublayersTableViewController.swift
- Changes type of `sublayers` from `NSMutableArray` to `[AGSArcGISMapImageSublayer]`
- Sizes the popover to fit the height of the table view's content
> Change Sublayer Visibility: Improves sublayers view

- arcgis-ios-sdk-samples/Content Display Logic/Controllers/SampleInfoViewController.swift
- arcgis-ios-sdk-samples/Content Display Logic/Model/SampleSearchEngine.swift
Rather than the global function.
> Uses NSRange initializer

- arcgis-ios-sdk-samples/Layers/Hillshade renderer/HillshadeRenderer.storyboard
- arcgis-ios-sdk-samples/Layers/Hillshade renderer/HillshadeSettingsVC.swift
Updates the Hillshade Renderer sample to use a right detail style for the slop type cell and use a number formatter for the labels
> Hillshade Renderer enhancements

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- arcgis-ios-sdk-samples/Content Display Logic/Controllers/Color Picker/ColorPicker.storyboard
- arcgis-ios-sdk-samples/Content Display Logic/Controllers/Color Picker/ColorPickerViewController.swift
- arcgis-ios-sdk-samples/Maps/Change map view background/ChangeMapViewBackground.storyboard
- arcgis-ios-sdk-samples/Maps/Change map view background/ChangeMapViewBackgroundVC.swift
- arcgis-ios-sdk-samples/Maps/Change map view background/GridSettingsViewController.swift
Also:
- Adds a reusable color picker view controller
> Converts the settings of Change Map View Background to a popover

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- arcgis-ios-sdk-samples/AppDelegate.swift
- arcgis-ios-sdk-samples/Cloud & Portal/Search for webmap by keyword/SearchForWebmapByKeywordViewController.swift
- arcgis-ios-sdk-samples/Content Display Logic/Controllers/ContentCollectionViewController.swift
- arcgis-ios-sdk-samples/Content Display Logic/Controllers/ContentTableViewController.swift
- arcgis-ios-sdk-samples/Content Display Logic/Storyboard/Main.storyboard
- arcgis-ios-sdk-samples/Edit data/Update geometries (feature service)/EditGeometryViewController.swift
Updates deployment target to iOS 11 and removes code that only ran on iOS 10.
> Removes support for iOS 10

- arcgis-ios-sdk-samples/Edit data/Offline edit and sync/FeatureLayersViewController.swift
- arcgis-ios-sdk-samples/Edit data/Offline edit and sync/OfflineEditing.storyboard
- arcgis-ios-sdk-samples/Edit data/Offline edit and sync/OfflineEditingViewController.swift
Also organizes and cleans up the sample's code somewhat, removing IUO for runtime objects.
> Updates Offline Map Edit and Sync to allow syncing without edits

- arcgis-ios-sdk-samples/Edit data/Offline edit and sync/OfflineEditingViewController.swift
- arcgis-ios-sdk-samples/Features/Generate geodatabase/GenerateGeodatabaseViewController.swift
- arcgis-ios-sdk-samples/Layers/ArcGIS tiled layer (tile cache)/TilePackagesListViewController.swift
- arcgis-ios-sdk-samples/Layers/Export tiles/ExportTilesViewController.swift
- arcgis-ios-sdk-samples/Maps/Mobile map (search and route)/MapPackagesListViewController.swift
Its usage is discouraged in the documentation.
> Removes usage of NSSearchPathForDirectoriesInDomains

- arcgis-ios-sdk-samples/Search/Find place/FindPlaceViewController.swift
This is a step toward potentially implementing the `type_body_length` SwiftLint rule.
> Moves protocol conformances to extensions in the Find Place sample

- arcgis-ios-sdk-samples/Edit data/Edit features (connected)/EditFeaturesOnlineViewController.swift
- arcgis-ios-sdk-samples/Edit data/Offline edit and sync/OfflineEditingViewController.swift
- arcgis-ios-sdk-samples/Search/Find address/FindAddressViewController.swift
- arcgis-ios-sdk-samples/Search/Find place/FindPlaceViewController.swift
- arcgis-ios-sdk-samples/Search/Offline geocode/OfflineGeocodeViewController.swift
- Removes unneeded notification center removeObserver calls
- Replaces general removeObserver call with preferred call for specific notification
> Notification center removeObserver improvements

- arcgis-ios-sdk-samples/Layers/ArcGIS tiled layer (tile cache)/LocalTiledLayer.storyboard
- arcgis-ios-sdk-samples/Layers/ArcGIS tiled layer (tile cache)/LocalTiledLayerViewController.swift
- arcgis-ios-sdk-samples/Layers/ArcGIS tiled layer (tile cache)/TilePackagesListViewController.swift
- arcgis-ios-sdk-samples/Maps/Manage bookmarks/Bookmarks.storyboard
- arcgis-ios-sdk-samples/Maps/Manage bookmarks/BookmarksListViewController.swift
- arcgis-ios-sdk-samples/Maps/Manage bookmarks/BookmarksViewController.swift
- arcgis-ios-sdk-samples/Maps/Read a geopackage/GPKGLayersViewController.swift
- arcgis-ios-sdk-samples/Maps/Read a geopackage/ReadGeopackage.storyboard
- arcgis-ios-sdk-samples/Maps/Read a geopackage/ReadGeopackageViewController.swift
Also minor usability improvements and code cleanup.
> Replaces tables with UITableViewController, first PR

- arcgis-ios-sdk-samples/Search/Find place/FindPlaceViewController.swift
This prevents it from polluting the global namespace.
> Makes SuggestionType a subtype of FindPlaceViewController

- arcgis-ios-sdk-samples/Content Display Logic/Controllers/SourceCodeViewController.swift
`weakSelf` was in fact `strong`.
> Renames weakSelf to self in SourceCodeViewController

- arcgis-ios-sdk-samples/Cloud & Portal/Search for webmap by keyword/SearchForWebmapByKeywordViewController.swift
The property is no longer needed.
> Remove SearchForWebmapByKeywordViewController.searchController

- arcgis-ios-sdk-samples/Layers/Change sublayer renderer/ChangeSublayerRendererVC.swift
This started out as an effort to rename `weakSelf` (which was in fact strong) to `self` (optionally bound). One change led to another and I ended up refactoring parts of the sample. The biggest change is the addition of a property for the counties sublayer.
> Refactor Change Sublayer Renderer view controller

- arcgis-ios-sdk-samples/Cloud & Portal/Search for webmap by keyword/SearchForWebmapByKeywordViewController.swift
The view controller has a date formatter property on line `77`. This is much more efficient than creating a new date formatter each time a cell is loaded.
> Search For Webmap by Keyword: Reuse view controller's date formatter

- arcgis-ios-sdk-samples/Features/Generate geodatabase/GenerateGeodatabaseViewController.swift
Also refactors code related to comment to be more efficient.
> Generate Geodatabase: Fix typo in comment

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
Xcode recommends these changes whenever a change is made to the project file.
> Update project file as recommended by Xcode

- arcgis-ios-sdk-samples/Layers/Browse WFS layers/WFSLayersTableViewController.swift
@saratchandrakarumuri @philium please review fix for an issue I ran into. Without this, the unselected cell still has a checkmark, if originally invisible.
> fix issue where invisible cell still had a checkmark after unselecting

- arcgis-ios-sdk-samples/Content Display Logic/Controllers/ListViewController.swift
This class was so small that I also went and turned `selectAction` into a non-IUO.
> Make ListViewController.list non-optional

- arcgis-ios-sdk-samples/Maps/Display layer view state/LayerStatusViewController.swift
- Create status string as needed.
- Include all statuses in the status string.
- Reload rows only for layers whose status has changed.
> Display Layer View State: Improvements to status handling

- arcgis-ios-sdk-samples/Maps/Manage operational layers/MMLLayersViewController.swift
Adheres Section to CaseIterable so as to leverage allCases.count in place of a static integer.
> Adheres Section to CaseIterable so as to leverage allCases.count

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
This is the default for new projects.
> Update project format to Xcode 9.3-compatible

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- arcgis-ios-sdk-samples/Content Display Logic/ContentPList.plist
- arcgis-ios-sdk-samples/Content Display Logic/FileTypes.plist
- arcgis-ios-sdk-samples/Content Display Logic/PortalItems.plist
- arcgis-ios-sdk-samples/Display information/Graphics overlay (dictionary renderer) 3D/GraphicsOverlayDictionaryRenderer3DViewController.swift
- arcgis-ios-sdk-samplesTests/Sample Tests/GraphicsOverlayDictionaryRenderer3DViewControllerTests.swift
> Use new AGSDictionarySymbolStyle initializer

- arcgis-ios-sdk-samples/Analysis/Analyze hotspots/README.metadata.json
- arcgis-ios-sdk-samples/Analysis/Distance measurement analysis/README.metadata.json
- arcgis-ios-sdk-samples/Analysis/Line of sight (geoelement)/README.metadata.json
- arcgis-ios-sdk-samples/Analysis/Line of sight (location)/README.metadata.json
- arcgis-ios-sdk-samples/Analysis/Statistical query (group and sort)/README.metadata.json
- arcgis-ios-sdk-samples/Analysis/Statistical query/README.metadata.json
- arcgis-ios-sdk-samples/Analysis/Viewshed (GeoElement)/README.metadata.json
- arcgis-ios-sdk-samples/Analysis/Viewshed (camera)/README.metadata.json
- arcgis-ios-sdk-samples/Analysis/Viewshed (geoprocessing)/README.metadata.json
- arcgis-ios-sdk-samples/Analysis/Viewshed (location)/README.metadata.json
The PR for the Analysis category to add metadata JSON files.
> Metadata PR for Analysis 

- arcgis-ios-sdk-samples/Scenes/Add a point scene layer/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/Add an integrated mesh layer/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/Animate 3D graphic/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/Change atmosphere effect/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/Choose camera controller/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/Create terrain surface from a local raster/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/Create terrain surface from a local tile package/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/Display a scene/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/Distance composite symbol/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/Extrude graphics/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/Feature layer extrusion/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/Open a scene (portal item)/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/Open mobile scene (scene package)/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/Scene layer (URL)/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/Scene layer selection/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/Scene properties expressions/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/Scene symbols/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/Surface placements/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/Sync map and scene views/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/Terrain exaggeration/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/View content beneath the terrain surface/README.metadata.json
- arcgis-ios-sdk-samples/Scenes/View point cloud data offline/README.metadata.json
> Metadata Migration: Scenes Category

- arcgis-ios-sdk-samples/Features/Add delete related features/README.metadata.json
- arcgis-ios-sdk-samples/Features/Change feature layer renderer/README.metadata.json
- arcgis-ios-sdk-samples/Features/Feature collection layer (query)/README.metadata.json
- arcgis-ios-sdk-samples/Features/Feature collection layer/README.metadata.json
- arcgis-ios-sdk-samples/Features/Feature layer (feature service)/README.metadata.json
- arcgis-ios-sdk-samples/Features/Feature layer (geodatabase)/README.metadata.json
- arcgis-ios-sdk-samples/Features/Feature layer (geopackage)/README.metadata.json
- arcgis-ios-sdk-samples/Features/Feature layer (shapefile)/README.metadata.json
- arcgis-ios-sdk-samples/Features/Feature layer definition expression/README.metadata.json
- arcgis-ios-sdk-samples/Features/Feature layer query/README.metadata.json
- arcgis-ios-sdk-samples/Features/Feature layer rendering mode (map)/README.metadata.json
- arcgis-ios-sdk-samples/Features/Feature layer rendering mode (scene)/README.metadata.json
- arcgis-ios-sdk-samples/Features/Feature layer selection/README.metadata.json
- arcgis-ios-sdk-samples/Features/Generate geodatabase/README.metadata.json
- arcgis-ios-sdk-samples/Features/List related features/README.metadata.json
- arcgis-ios-sdk-samples/Features/Service feature table (cache)/README.metadata.json
- arcgis-ios-sdk-samples/Features/Service feature table (manual cache)/README.metadata.json
- arcgis-ios-sdk-samples/Features/Service feature table (no cache)/README.metadata.json
- arcgis-ios-sdk-samples/Features/Time based query/README.metadata.json
@philium here are the `Features` sample code categories.
> Metadata PR for Features - fix tags and image order

- arcgis-ios-sdk-samples/Edit data/Offline edit and sync/README.metadata.json
Adding missing comma so samples will build.
> Missing comma in metadata files

- arcgis-ios-sdk-samples/Layers/Control annotation sublayer visibility/README.metadata.json
- arcgis-ios-sdk-samples/Route & Directions/Find closest facility to multiple incidents (service)/README.metadata.json
- arcgis-ios-sdk-samples/Utility Network/Connected Trace/README.metadata.json
@philium and @maryharvey -- here are the three missing metadata files that Philip pointed out.
> Missing metadata files

- arcgis-ios-sdk-samples/Edit data/Edit and sync features/EditAndSyncFeaturesViewController.swift
Also refactors logic that tests a string to determine application state.
@vquach2404 If you accept this PR it'll update your PR branch to address the two issues I had mentioned in your PR review.
> Simplify Selection logic

- arcgis-ios-sdk-samples/AppDelegate.swift
- arcgis-ios-sdk-samples/Info.plist
This fixes and issue where the background color and tint color were the same. Also disabled dark mode as we don't support it yet.
> Update navigation bar appearance for iOS 13

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
I've confirmed that the changes in this PR fix the following error:
I was able to successfully clone and build from this branch.
> Re-add ArcGISToolkit to Embed Frameworks build phase

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- arcgis-ios-sdk-samples/Cloud & Portal/Search for webmap by keyword/SearchForWebmapByKeywordViewController.swift
- arcgis-ios-sdk-samples/Content Display Logic/Controllers/ContentCollectionViewController.swift
https://devtopia.esri.com/runtime/common-samples/issues/1657
Workaround iOS 13 issue with searchController.
> fix navigation bar jumbled mess issue on iOS 13

- arcgis-ios-sdk-samples/Layers/Group layers/GroupLayersViewController.swift
* Updated the old services used in Group layers sample
* Added offset and scene properties to pathways as per issue comments
> Updated outdated services in Group layers sample

- arcgis-ios-sdk-samples/Edit data/Edit and sync features/EditAndSyncFeaturesViewController.swift
> Remove usage of AGSFeatureTable.featureLayer

- arcgis-ios-sdk-samples/Scenes/Open mobile scene (scene package)/OpenMobileSceneViewController.swift
The unpack workflow has been deprecated as it is no longer necessary.
> Open Mobile Scene (Scene Package): Remove unpack workflow

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- arcgis-ios-sdk-samples/Content Display Logic/ContentPList.plist
- arcgis-ios-sdk-samples/Edit data/Update attributes (feature service)/UpdateAttributes.storyboard
- arcgis-ios-sdk-samples/Edit data/Update attributes (feature service)/UpdateAttributesOptionsViewController.swift
- arcgis-ios-sdk-samples/Edit data/Update attributes (feature service)/UpdateAttributesViewController.swift
- `EditAttributesViewController` -> `UpdateAttributesViewController`
- `EAOptionsViewController` -> `UpdateAttributesOptionsViewController`
- `EAOptionsVCDelegate` -> `UpdateAttributesOptionsViewControllerDelegate`
> Update Attributes (Feature Service): Rename classes and delegate

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
Xcode keeps suggesting this change whenever a change is made to the project file.
> Make Xcode happy

- arcgis-ios-sdk-samples/Edit data/Update attributes (feature service)/README.metadata.json
- arcgis-ios-sdk-samples/Features/Feature collection layer (query)/README.metadata.json
- arcgis-ios-sdk-samples/Features/Feature collection layer/README.metadata.json
- arcgis-ios-sdk-samples/Route & Directions/Find service area interactive/README.metadata.json
I forgot to do this along the way. I'll add this to my rename checklist.
> Update metadata files for renamed files

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- arcgis-ios-sdk-samples/Layers/Hillshade renderer/HillshadeRenderer.storyboard
- arcgis-ios-sdk-samples/Layers/Hillshade renderer/HillshadeRendererViewController.swift
- arcgis-ios-sdk-samples/Layers/Hillshade renderer/HillshadeSettingsViewController.swift
- arcgis-ios-sdk-samples/Layers/Hillshade renderer/README.metadata.json
- `HillshadeRendererVC` -> `HillshadeRendererViewController`
- `HillshadeSettingsVC` -> `HillshadeSettingsViewController`
- `HillshadeSettingsDelegate` -> `HillshadeSettingsViewControllerDelegate`
> Rename Hillshade Renderer sample types

- README.md
- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- arcgis-ios-sdk-samples/Augmented reality/Display scenes in tabletop AR/DisplayScenesInTabletopAR.swift
The next version of ArcGIS will not support iOS 11.
> Remove support for iOS 11

- arcgis-ios-sdk-samples/Scenes/Surface placements/SurfacePlacementsViewController.swift
> Surface Placements: Update camera to better emphasize draped flat

- arcgis-ios-sdk-samples/Maps/Generate offline map (basemap by reference)/GenerateOfflineMapBasemapByReferenceViewController.swift
Found a typo in the source code.
> Fix: Typo in the GenerateOfflineMap sample

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- arcgis-ios-sdk-samples/Info.plist
These are changes Xcode wants to make whenever the project file is modified. And whenever the version number is modified, Xcode moves it out of the info plist and into the project.
> Various project changes

- arcgis-ios-sdk-samples/Geometry/Convex hull/ConvexHullViewController.swift
- arcgis-ios-sdk-samples/Geometry/Nearest vertex/NearestVertexViewController.swift
Updated 100.8 to fix a couple of typos.
> Fixed typos in 100.8

- arcgis-ios-sdk-samples/Layers/Control annotation sublayer visibility/README.md
- arcgis-ios-sdk-samples/Layers/Export tiles/README.md
- arcgis-ios-sdk-samples/Layers/Web tiled layer/README.md
- arcgis-ios-sdk-samples/Maps/Generate offline map (overrides)/README.md
- arcgis-ios-sdk-samples/Maps/Generate offline map/README.md
- arcgis-ios-sdk-samples/Maps/Map loaded/README.md
**Ref**: /common-samples/issues/1823
Fix the lingering issues spotted by samples team during cleaning up READMEs.
> Fix: "Gotchas" in README updates

- arcgis-ios-sdk-samples/Route & Directions/Navigate route/NavigateRouteViewController.swift
Revisiting this sample I implemented earlier, I spotted a few negligent copy-paste issues in the comment.
Sorry for introducing them in the first place! 😓
> Fix: Update comments in Navigate route

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
These changes are automatically made by Xcode whenever the project file is modified.
> Update Xcode project

- arcgis-ios-sdk-samples/Route & Directions/Navigate route/NavigateRouteViewController.swift
Refer to #837 and #883 . This PR fix coding style in the `Navigate route` sample.
Also as an additional effort to #890 , to make this sample better gradually.
> Fix: Navigate route

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
Make the project file changes Xcode wants after a new sample get merged into `v.next`.
> Fix : Make Xcode Happy

- arcgis-ios-sdk-samples/Cloud & Portal/Token authentication/README.md
- arcgis-ios-sdk-samples/Features/Feature layer (shapefile)/README.md
- arcgis-ios-sdk-samples/Scenes/Animate images with image overlay/README.md
ref: /runtime/common-samples/issues/2110
This PR "encapsulate the work to update the changes made to the common-samples repo", from May 4th through July 14th.
> Update: keep documentation up-to-date

- arcgis-ios-sdk-samples/Geometry/List transformations/README.md
ref: `/common-samples/issues/2154`.
This PR updates changes in design doc.
> Update: List transformation README

- README.md
- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- arcgis-ios-sdk-samples/Info.plist
- podfile
These changes prepare v.next to be merged into master. The content plist change came alongside with the project file update automatically.
> Updated readme and project file

- arcgis-ios-sdk-samples/Content Display Logic/ContentPList.plist
- arcgis-ios-sdk-samples/Edit data/Edit features with feature-linked annotation/README.md
- arcgis-ios-sdk-samples/Edit data/Edit features with feature-linked annotation/README.metadata.json
With #919  merged, this PR runs automated check on docs and fixed minor issues.
Will either setup sanity checks in our repo in next release, or periodically check docs formatting in the future.
> Fix: Formatting issues in docs

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- arcgis-ios-sdk-samples/Features/List related features/ListRelatedFeatures.storyboard
- arcgis-ios-sdk-samples/Features/List related features/ListRelatedFeaturesViewController.swift
- arcgis-ios-sdk-samples/Features/List related features/README.metadata.json
- arcgis-ios-sdk-samples/Features/List related features/RelatedFeaturesListViewController.swift
This is part of the effort to rename all VC abbreviations.
> Rename List Related Features

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- arcgis-ios-sdk-samples/Layers/Raster layer (service)/README.metadata.json
- arcgis-ios-sdk-samples/Layers/Raster layer (service)/RasterLayerUsingService.storyboard
- arcgis-ios-sdk-samples/Layers/Raster layer (service)/RasterLayerUsingServiceViewController.swift
Renamed Raster layer (service)
> Renamed raster layer using service

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- arcgis-ios-sdk-samples/Route and directions/Find service area interactive/FindServiceAreaInteractive.storyboard
- arcgis-ios-sdk-samples/Route and directions/Find service area interactive/FindServiceAreaInteractiveViewController.swift
- arcgis-ios-sdk-samples/Route and directions/Find service area interactive/README.metadata.json
- arcgis-ios-sdk-samples/Route and directions/Find service area interactive/ServiceAreaSettingsViewController.swift
Renamed files, functions, class, metadata.
> Renamed Find service area interactive

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- arcgis-ios-sdk-samples/Layers/ArcGIS vector tiled layer (custom style)/README.metadata.json
- arcgis-ios-sdk-samples/Layers/ArcGIS vector tiled layer (custom style)/VectorTileCustomStyle.storyboard
- arcgis-ios-sdk-samples/Layers/ArcGIS vector tiled layer (custom style)/VectorTileCustomStyleViewController.swift
Renamed the class, files, and metadata.
> Renamed Vector tiled layer custom style

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- arcgis-ios-sdk-samples/Analysis/Viewshed (location)/README.metadata.json
- arcgis-ios-sdk-samples/Analysis/Viewshed (location)/ViewshedLocation.storyboard
- arcgis-ios-sdk-samples/Analysis/Viewshed (location)/ViewshedLocationViewController.swift
- arcgis-ios-sdk-samples/Analysis/Viewshed (location)/ViewshedSettingsViewController.swift
Updated files, class, metadata.
> Rename Viewshed location

- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
Xcode makes these changes automatically.
> Fix: Make Xcode happy

- arcgis-ios-sdk-samples/Edit data/Edit features with feature-linked annotation/EditFeaturesWithFeatureLinkedAnnotationViewController.swift
- arcgis-ios-sdk-samples/Edit data/Edit with branch versioning/EditWithBranchVersioningViewController.swift
- arcgis-ios-sdk-samples/Utility Network/Configure subnetwork trace/ConfigureSubnetworkTraceOptionsViewController.swift
This PR fixes the memory leaks caused by alert retain cycles.
> Fixed memory leaks caused by retain cycles

- arcgis-ios-sdk-samples/Display information/Read symbols from a mobile style/ReadSymbolsFromMobileStyleSymbolSettingsViewController.swift
This PR fixes the deprecation warning in `ReadSymbolsFromMobileStyleSymbolSettingsViewController`.
> Fix: Address deprecation warning

- arcgis-ios-sdk-samples/Analysis/Analyze hotspots/AnalyzeHotspotsViewController.swift
- arcgis-ios-sdk-samples/Analysis/Analyze hotspots/HotspotSettingsViewController.swift
- arcgis-ios-sdk-samples/Augmented reality/Collect data in AR/CollectDataAR.swift
- arcgis-ios-sdk-samples/Augmented reality/Navigate in AR/NavigateARNavigatorViewController.swift
- arcgis-ios-sdk-samples/Augmented reality/Navigate in AR/NavigateARRoutePlannerViewController.swift
- arcgis-ios-sdk-samples/Augmented reality/View hidden infrastructure in AR/ViewHiddenInfrastructureARExplorerViewController.swift
- arcgis-ios-sdk-samples/Content Display Logic/Controllers/SegmentedViewController.swift
- arcgis-ios-sdk-samples/Content Display Logic/Custom BarButtonItem/SourceCodeBarButtonItem.swift
- arcgis-ios-sdk-samples/Edit data/Edit features (connected)/EditFeaturesOnlineViewController.swift
- arcgis-ios-sdk-samples/Edit data/Offline edit and sync/OfflineEditingViewController.swift
- arcgis-ios-sdk-samples/Layers/ArcGIS vector tiled layer (custom style)/VectorStylesViewController.swift
- arcgis-ios-sdk-samples/Layers/ArcGIS vector tiled layer (custom style)/VectorTileCustomStyleViewController.swift
- arcgis-ios-sdk-samples/Layers/Blend renderer/BlendRendererViewController.swift
- arcgis-ios-sdk-samples/Maps/Create and save a map/CreateSaveMapViewController.swift
- arcgis-ios-sdk-samples/Maps/Manage bookmarks/BookmarksViewController.swift
- arcgis-ios-sdk-samples/Scenes/Animate 3D graphic/Animate3DGraphicViewController.swift
- arcgis-ios-sdk-samples/Scenes/Animate 3D graphic/MissionSettingsViewController.swift
- arcgis-ios-sdk-samples/Search/Find address/FindAddressViewController.swift
- arcgis-ios-sdk-samples/Search/Find address/WorldAddressesViewController.swift
- arcgis-ios-sdk-samples/Search/Offline geocode/OfflineGeocodeViewController.swift
- arcgis-ios-sdk-samples/Search/Offline geocode/SanDiegoAddressesViewController.swift
This PR fixes most remaining "VC" abbreviation in source code and replace them with "ViewController".
> Fix: Change view controller abbreviation

- arcgis-ios-sdk-samples/Edit data/Edit with branch versioning/EditWithBranchVersioningViewController.swift
- arcgis-ios-sdk-samples/Maps/Display device location/DisplayLocationSettingsViewController.swift
- arcgis-ios-sdk-samples/Maps/Display layer view state/LayerStatusViewController.swift
Issues showed up after upgrading to [SwiftLint 0.41.0](https://github.com/realm/SwiftLint/releases/tag/0.41.0).
> Address linting issues

- .gitignore
- README.md
- Scripts/masquerade
- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- arcgis-ios-sdk-samples.xcodeproj/xcshareddata/xcschemes/arcgis-ios-sdk-samples.xcscheme
- arcgis-ios-sdk-samples/AppDelegate.swift
- arcgis-ios-sdk-samples/AppSecrets.swift.masque
This PR sets up the *masquerade* mechanism similar to Esri's [Data Collection app](https://github.com/Esri/data-collection-ios/tree/master/docs#app-secrets) maintained by @esreli . This mechanism will allow users to easily keep their License Key and API Key secrets out of source control, to avoid [leaking](https://github.com/search?q=ArcGISRuntime.setLicense%28%22&type=code) the secrets, as in U10 the secrets have more capabilities.
1. Set up the masquerade mechanism in sample viewer without obfuscation
This step copies the *masquerade* tool from Data Collection app and set it up for the sample viewer.
2. Write a doc for developers to guide them
1. how to set API secrets to build the sample viewer
The instructions are in the root README.
2. how to set masquerade in their own project if …
> New: Adding API keys with "masquerade" mechanism

- README.md
- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- podfile
This PR will update related files for U10 release.
- Update the minimum version
- Remove `latest` from URL pattern to cope with the new doc site
- Adjust wordings for CocoaPods
> [Update] Preparations for U10 release

- README.md
- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
This PR updates the version numbers, and get ready for the 100.11.1 App Store release.
> Update: 100.11.1 version numbers

- arcgis-ios-sdk-samples/Utility network/Configure subnetwork trace/ConfigureSubnetworkTraceViewController.swift
- arcgis-ios-sdk-samples/Utility network/Create load report/CreateLoadReportViewController.swift
- arcgis-ios-sdk-samples/Utility network/Create load report/README.md
- arcgis-ios-sdk-samples/Utility network/Perform valve isolation trace/PerformValveIsolationTraceViewController.swift
- arcgis-ios-sdk-samples/Utility network/Trace utility network/README.md
- arcgis-ios-sdk-samples/Utility network/Trace utility network/TraceUtilityNetworkViewController.swift
This PR replaces the deprecated UN property. Please see `common-samples/issues/2754` for more information.
> Update: Replace deprecated Utility Network property

- README.md
- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- podfile
Similar to #1053 . This PR bumps the version number for U12 release.
- Podfile
- Project file toolkit `upToNextMinorVersion`
- Root README
> Update: Bump version number for Update 12

- arcgis-ios-sdk-samples/Maps/Display device location with NMEA data sources/README.md
This PR updates the NMEA sample, to include additional protocol strings, for developers' reference & convenience.
This is a doc only change.
`common-samples/issues/3283`
No need to test - this is a doc only change.
> Update: Add NMEA Bluetooth protocol strings

- arcgis-ios-sdk-samples/Maps/Browse building floors/BrowseBuildingFloorsViewController.swift
- arcgis-ios-sdk-samples/Maps/Browse building floors/README.md
This PR implements `Browse building floors` in `maps` category, to address several feedback from Nathan. README will be updated when the design PR gets merged
`common-samples/issues/3321`
The sample should behave exactly the same as before.
> Update: `Browse building floors` the way to select first floor

- .github/PULL_REQUEST_TEMPLATE.md
This PR updates the PR template to make it easier to use.
Had a discussion with Viv and we agreed that there is no need to keep the sections commented out. Given that we need to remove unused section from the template anyway, it is easier to just leave them as visible text so that there is no need to first delete the comment strings, then reindent before starting to write.
> [Logistics] Uncomment PR template content

- arcgis-ios-sdk-samples/Edit data/Add features (feature service)/README.md
- arcgis-ios-sdk-samples/Edit data/Add features (feature service)/README.metadata.json
- arcgis-ios-sdk-samples/Edit data/Delete features (feature service)/README.md
- arcgis-ios-sdk-samples/Edit data/Delete features (feature service)/README.metadata.json
- arcgis-ios-sdk-samples/Edit data/Edit features (connected)/README.md
- arcgis-ios-sdk-samples/Edit data/Edit features (connected)/README.metadata.json
- arcgis-ios-sdk-samples/Edit data/Update attributes (feature service)/README.md
- arcgis-ios-sdk-samples/Edit data/Update attributes (feature service)/README.metadata.json
- arcgis-ios-sdk-samples/Edit data/Update geometries (feature service)/README.md
- arcgis-ios-sdk-samples/Edit data/Update geometries (feature service)/README.metadata.json
This PR is the 3rd in the series to update `applyEdits` related stuff. See #1148 and #1151 .
- `common-samples/issues/3371`
doc only change.
> [Update] Apply edits READMEs

- arcgis-ios-sdk-samples/Scenes/Show labels on layer in 3D/ShowLabelsOnLayer3DViewController.swift
This PR fixes a bug in the Show labels on layer in 3D sample. The data seems to have changed sometime after the original implementation. The change in data made the code outdated.
Branch: https://github.com/Esri/arcgis-runtime-samples-ios/tree/Viv/fix3DLabel
- `common-samples/3451`
Check to ensure the labels are shown in the Show labels on layer in 3D sample.
> Bug fix: Show labels on layer in 3D

- arcgis-ios-sdk-samples/Layers/List KML contents/ListKMLContentsSceneViewController.swift
This PR fixes a wrong usage of basemap introduced in #1157 
- `common-samples/issues/3490`
> [Fix] Basemap style in ListKMLContentsSceneViewController.swift

- arcgis-ios-sdk-samples/Maps/Apply scheduled updates to preplanned map area/ApplyScheduledUpdatesToPreplannedMapAreaViewController.swift
This PR updates the workflow, to recreate the mmpk when updates are received.
This is due to a recent change in core.
See also: https://github.com/Esri/arcgis-runtime-samples-java/pull/684
- `common-samples/issues/3489`
Use daily build...
- See the updates are not displaying on `v.next`
- See the updates are displaying on map on this branch
https://user-images.githubusercontent.com/9660181/164774634-df775b6a-344d-448d-ab8f-9b1d9f8b91e6.mp4
> [Update] `Apply scheduled updates to preplanned map area` reload mmpk

- arcgis-ios-sdk-samples/Layers/Raster layer (service)/README.md
- arcgis-ios-sdk-samples/Layers/Raster layer (service)/RasterLayerUsingServiceViewController.swift
This PR fixes an invalid raster image service.
- `common-samples/issues/3499`
- `common-samples/issues/3503`
Old doesn't work, new works.
It does take a few seconds to load though.
> [Update] Raster service data URL

- README.md
- arcgis-ios-sdk-samples.xcodeproj/project.pbxproj
- podfile
This PR bumps version number for U14, getting ready for release.
> [Update] Bump version number for U14

- arcgis-ios-sdk-samples/Features/Display feature layers/DisplayFeatureLayersViewController.swift
- arcgis-ios-sdk-samples/Features/Display feature layers/README.md
This PR updates the  `Display feature layers` in `Features` category.
Branch: [URL_TO_BRANCH](https://github.com/Esri/arcgis-runtime-samples-ios/tree/Viv/enhanceFeatureLayers)
- `common-samples/issues/3542`
> Update: Display feature layers

- arcgis-ios-sdk-samples/Maps/Generate offline map/GenerateOfflineMapViewController.swift
This PR implements `Generate offline map` in `Maps` category.
> Fix: Remove extra return

- arcgis-ios-sdk-samples/Layers/Query with CQL filters/QueryWithCQLFiltersSettingsViewController.swift
This PR updates `Query with CQL filters` in `Layers` category.
- `common-samples/issues/3461`
Test build with latest U15 daily. Before this update it shows Bad Request for the JSONs.
The results for the 4 queries
- 75
- 75 (because the JSON is the equivalent to the plain text query)
- 99
- 64
> [Update] CQL query to CQL2-JSON schema

- arcgis-ios-sdk-samples/Analysis/Viewshed (location)/ViewshedLocationViewController.swift
- arcgis-ios-sdk-samples/Augmented reality/View hidden infrastructure in AR/ViewHiddenInfrastructureARCalibrationViewController.swift
- arcgis-ios-sdk-samples/Geometry/Clip geometry/ClipGeometryViewController.swift
- arcgis-ios-sdk-samples/Geometry/Cut geometry/CutGeometryViewController.swift
- arcgis-ios-sdk-samples/Maps/Manage bookmarks/BookmarksListViewController.swift
This PR implements fixes various linter warnings.
> [Fix] Linter warnings

- README.md
https://github.com/Esri/arcgis-runtime-samples-ios/issues/1202
> Adding note about 200
